<template>
    <ValidationObserver ref="validatorRef">
        <div class="formFieldsInformations">  {{ $t("Move.requiredFieldInformation") }} </div>

        <p>
            <b> {{ $t("Move.location") }}</b>
        </p>
        <hr/>

        <div class="row">
            <div class="col-lg-5">
                <opensilex-FacilitySelector
                        ref="moveFromSelector"
                        label="Position.from"
                        :facilities.sync="form.from"
                        :multiple="false"
                        :required="fromRequired"
                        @select="updateRequiredProps()"
                        @clear="updateRequiredProps()"
                        helpMessage="Position.from-help"
                ></opensilex-FacilitySelector>
            </div>
            <div class="col-lg-5">
                <opensilex-FacilitySelector
                        ref="moveToSelector"
                        label="Position.to"
                        :facilities.sync="form.to"
                        :multiple="false"
                        :required="toRequired"
                        @select="updateRequiredProps()"
                        @clear="updateRequiredProps()"
                        helpMessage="Position.to-help"
                ></opensilex-FacilitySelector>
            </div>
        </div>

        <div>
            <p><b> {{ $t("Position.title") }}</b></p>
            <hr/>
            <opensilex-PositionForm 
               :form.sync="form.targets_positions[0].position">
            </opensilex-PositionForm>
        </div>

    </ValidationObserver>
</template>

<script lang="ts">
    import {Component, Prop, Ref} from "vue-property-decorator";
    import Vue from "vue";
    import PositionForm from "../../positions/form/PositionForm.vue";
    import { MoveCreationDTO, TargetPositionCreationDTO } from 'opensilex-core/index';
    import OpenSilexVuePlugin from "../../../models/OpenSilexVuePlugin";
    import VueI18n from "vue-i18n";


    @Component
    export default class MoveForm extends Vue {

        @Ref("validatorRef") readonly validatorRef!: any;

        editMode = false;
        fromRequired: boolean = false;
        toRequired: boolean = false;
        $opensilex: OpenSilexVuePlugin;
        $i18n: VueI18n;

        @Prop({default: () => MoveForm.getEmptyForm()})
        form: MoveCreationDTO;

        static getEmptyTargetsPositions() : Array<TargetPositionCreationDTO> {
            return  [{
                    target: undefined,
                    position : PositionForm.getEmptyForm()
                }];
         }

        static getEmptyForm() : MoveCreationDTO{
            return {
              uri: undefined,
              rdf_type: undefined,
              start: undefined,
              end: undefined,
              is_instant: true,
              description: undefined,
              targets: [],

              relations: [],

              // move specific properties
                from: undefined,
                to: undefined,

                // move position(s)
              targets_positions: MoveForm.getEmptyTargetsPositions()
            };
        }

        getEmptyForm() {
            return MoveForm.getEmptyForm();
        }

        created(){
        }


        reset() {
            return this.validatorRef.reset();
        }

        validate() {
            return this.validatorRef.validate();
        }

        /**
         * The "From" field is optional, and becomes required from the moment the "To" field is completed.
         */
        updateRequiredProps() {
            if(this.form.from == undefined 
            && this.form.to == undefined 
            && this.form.targets_positions[0].position !== undefined 
            && this.form.targets_positions[0].position !== "") {
                this.fromRequired = false;
                this.toRequired = false; 
            } else {
                 this.toRequired = true;
            }
        }

        handleSubmitError(){
            if(!this.form.to && !this.form.targets_positions[0]){
                this.$opensilex.showErrorToast(this.$i18n.t("Move.fieldRequired").toString()); 
            }
        }
    }
</script>

<style scoped lang="scss">
.formFieldsInformations{
    background-color: #d1ecf1;
    color: #2D7580;
    padding: 5px;
    font-weight: 600;
    margin-bottom: 10px;
}

</style>

<i18n>
en:
    Move:
        add: Move
        location: Location
        uri-help: Move URI (autogenerated if empty)
        type-help: Move type
        requiredFieldInformation: At least one of the following field informations is required to declare the element
fr:
    Move:
        add: Déplacer
        location: Localisation
        uri-help: URI du déplacement (auto-générée si vide)
        type-help: Type de déplacement
        requiredFieldInformation: Au moins l'un des champs suivants doit être renseigné pour déclarer l'élément
</i18n>

