<template>
    <ValidationObserver ref="validatorRef">
        <div class="formFieldsInformations">  {{ $t("Move.requiredFieldInformation") }} </div>

        <p>
            <b> {{ $t("Move.location") }}</b>
        </p>
        <hr/>

      <opensilex-LocationForm
        :form.sync="form.location"
        :isMove="true"
        :displayDateFields="false"
      >
      </opensilex-LocationForm>

    </ValidationObserver>
</template>

<script lang="ts">
    import {Component, Prop, Ref} from "vue-property-decorator";
    import Vue from "vue";
    import { MoveCreationDTO } from 'opensilex-core/index';
    import OpenSilexVuePlugin from "../../../models/OpenSilexVuePlugin";
    import VueI18n from "vue-i18n";


    @Component
    export default class MoveForm extends Vue {

        @Ref("validatorRef") readonly validatorRef!: any;

        editMode = false;
        fromRequired: boolean = false;
        toRequired: boolean = false;
        $opensilex: OpenSilexVuePlugin;
        $i18n: VueI18n;

        @Prop({default: () => MoveForm.getEmptyForm()})
        form: MoveCreationDTO;

        static getEmptyForm() : MoveCreationDTO{
            return {
              uri: undefined,
              rdf_type: undefined,
              start: undefined,
              end: undefined,
              is_instant: true,
              description: undefined,
              targets: [],

              relations: [],

              // move specific properties
              location:{}
            };
        }

        getEmptyForm() {
            return MoveForm.getEmptyForm();
        }

        created(){
        }


        reset() {
            return this.validatorRef.reset();
        }

        validate() {
            return this.validatorRef.validate();
        }

    }
</script>

<style scoped lang="scss">
.formFieldsInformations{
    background-color: #d1ecf1;
    color: #2D7580;
    padding: 5px;
    font-weight: 600;
    margin-bottom: 10px;
}

</style>

<i18n>
en:
    Move:
        add: Move
        location: Location
        uri-help: Move URI (autogenerated if empty)
        type-help: Move type
        requiredFieldInformation: At least one of the following field informations is required to declare the element
fr:
    Move:
        add: Déplacer
        location: Localisation
        uri-help: URI du déplacement (auto-générée si vide)
        type-help: Type de déplacement
        requiredFieldInformation: Au moins l'un des champs suivants doit être renseigné pour déclarer l'élément
</i18n>

