<template>
  <n-form
    ref="formRef"
    :model="form"
    label-placement="top"
    :show-require-mark="true"
  >
    <div class="formFieldsInformations">
      {{ t("Move.requiredFieldInformation") }}
    </div>

    <p>
      <b>{{ t("Move.location") }}</b>
    </p>
    <hr />

    <opensilex-LocationForm
      v-model:form="form.location"
      :isMove="true"
      :displayDateFields="false"
    />
  </n-form>
</template>

<script setup lang="ts">
import { ref, withDefaults } from 'vue'
import type { FormInst } from 'naive-ui'
import { NForm } from 'naive-ui'
import type { MoveCreationDTO } from 'opensilex-core/index'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const props = withDefaults(defineProps<{
  form: MoveCreationDTO
}>(), {
  form: () =>
    ({
      uri: undefined,
      rdf_type: undefined,
      start: undefined,
      end: undefined,
      is_instant: true,
      description: undefined,
      targets: [],
      relations: [],
      location: {}
    } as MoveCreationDTO)
})

const formRef = ref<FormInst | null>(null)
const form = props.form

function getDefaultForm(): MoveCreationDTO {
  return {
    uri: undefined,
    rdf_type: undefined,
    start: undefined,
    end: undefined,
    is_instant: true,
    description: undefined,
    targets: [],
    relations: [],
    location: {}
  } as MoveCreationDTO
}

function getEmptyForm() {
  return getDefaultForm()
}

// function reset() {
// }

async function validate() {
  try {
    await formRef.value?.validate()
    return true
  } catch {
    return false
  }
}

defineExpose({
  getEmptyForm,
  // reset,
  validate
})
</script>

<style scoped lang="scss">
.formFieldsInformations {
  background-color: #d1ecf1;
  color: #2D7580;
  padding: 5px;
  font-weight: 600;
  margin-bottom: 10px;
}
</style>

<i18n>
en:
  Move:
    add: Move
    location: Location
    uri-help: Move URI (autogenerated if empty)
    type-help: Move type
    requiredFieldInformation: At least one of the following field informations is required to declare the element
fr:
  Move:
    add: Déplacer
    location: Localisation
    uri-help: URI du déplacement (auto-générée si vide)
    type-help: Type de déplacement
    requiredFieldInformation: Au moins l'un des champs suivants doit être renseigné pour déclarer l'élément
</i18n>