<template>
  <b-modal ref="modalRef" @ok.prevent="validate" size="xl" :static="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <ValidationObserver ref="validatorRef">
      <b-form>
        <!-- URI -->
        <b-form-group
          :label="$t('component.infrastructure.infrastructure-uri') + ':'"
          label-for="uri"
        >
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox
              v-if="!editMode"
              id="autogenerated"
              v-model="uriGenerated"
              name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider
            name="uri"
            rules="required_if:autogenerated,false|url"
            v-slot="{ errors }"
          >
            <b-form-input
              id="uri"
              v-model="form.uri"
              :disabled="uriGenerated"
              type="text"
              required
              :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Name -->
        <b-form-group :label="$t('component.common.name') + ':'" label-for="name" required>
          <ValidationProvider
            :name="$t('component.common.name')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-input
              id="name"
              v-model="form.name"
              type="text"
              required
              :placeholder="$t('component.infrastructure.form-name-placeholder')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Type -->
        <b-form-group :label="$t('component.common.type') + ':'" label-for="type" required>
          <ValidationProvider
            :name="$t('component.common.type')"
            rules="required"
            v-slot="{ errors }"
          >
            <treeselect
              id="type"
              :options="infraTypesOptions"
              :load-options="loadInfraTypes"
              :placeholder="$t('component.infrastructure.form-type-placeholder')"
              v-model="form.type"
            />
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Parent -->
        <b-form-group :label="$t('component.common.parent') + ':'" label-for="parent">
          <treeselect
            id="parent"
            :options="parentOptions"
            :placeholder="$t('component.infrastructure.form-parent-placeholder')"
            v-model="form.parent"
          />
        </b-form-group>
        <!-- Users -->
        <opensilex-GroupUserProfileForm ref="userProfilesRef" :userProfiles="form.userProfiles"></opensilex-GroupUserProfileForm>
      </b-form>
    </ValidationObserver>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import HttpResponse, { OpenSilexResponse } from "../../lib/HttpResponse";
import Oeso from "../../ontologies/Oeso";
import GroupUserProfileForm from "../groups/GroupUserProfileForm.vue";
import { OntologyService, InfrastructureGetDTO, InfrastructureCreationDTO, ResourceTreeDTO } from "opensilex-core/index";

@Component
export default class InfrastructureForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;
  $i18n: any;
  $t: any;
  service: OntologyService;

  @Prop()
  public defaultParent: InfrastructureGetDTO;

  @Prop()
  public parentOptions: Array<any>;

  @Ref("userProfilesRef") readonly userProfilesRef!: any;

  @Ref("modalRef") readonly modalRef!: any;

  @Ref("validatorRef") readonly validatorRef!: any;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  form: InfrastructureCreationDTO = {
    uri: "",
    type: null,
    name: "",
    parent: null,
    userProfiles: []
  };

  infraTypesOptions = null;

  title = "";

  editMode = false;

  created() {
    this.service = this.$opensilex.getService(
      "opensilex-security.OntologyService"
    );
  }

  loadInfraTypes({ action, parentNode, callback }) {
    this.service
      .getSubClassesOf(
        Oeso.INFRASTRUCTURE_TYPE_URI,
        true
      )
      .then((http: HttpResponse<OpenSilexResponse<Array<ResourceTreeDTO>>>) => {
        this.infraTypesOptions = this.$opensilex.buildTreeListOptions(
          http.response.result,
          callback()
        );
      })
      .catch(this.$opensilex.errorHandler);
  }

  clearForm() {
    let parentURI = null;
    if (this.defaultParent) {
      parentURI = this.defaultParent.uri;
    }
    this.form = {
      uri: "",
      type: null,
      name: "",
      parent: parentURI,
      userProfiles: []
    };
    this.userProfilesRef.clearForm();
  }

  showCreateForm(parentURI) {
    this.clearForm();
    this.form.parent = parentURI;
    this.editMode = false;
    this.title = this.$t("component.infrastructure.add").toString();
    this.uriGenerated = true;
    this.$opensilex.filterItemTree(this.parentOptions, this.form.uri);
    this.validatorRef.reset();
    this.modalRef.show();
  }

  showEditForm(form: InfrastructureCreationDTO) {
    this.form = form;
    this.userProfilesRef.initFormProfiles(form.userProfiles);
    this.editMode = true;
    this.title = this.$t("component.infrastructure.update").toString();
    this.uriGenerated = true;
    this.$opensilex.filterItemTree(this.parentOptions, this.form.uri);
    let modalRef: any = this.modalRef;
    this.validatorRef.reset();
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.modalRef;
    modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    let validatorRef: any = this.validatorRef;
    validatorRef.validate().then(isValid => {
      if (isValid) {
        if (this.uriGenerated && !this.editMode) {
          this.form.uri = null;
        }

        this.onValidate()
          .then(() => {
            this.$nextTick(() => {
              let modalRef: any = this.modalRef;
              modalRef.hide();
            });
          })
          .catch(error => {
            if (error.status == 409) {
              console.error("Infrastructure already exists", error);
              this.$opensilex.errorHandler(
                error,
                this.$i18n.t(
                  "component.infrastructure.errors.infrastructure-already-exists"
                )
              );
            } else {
              this.$opensilex.errorHandler(error);
            }
          });
      }
    });
  }
}
</script>

<style scoped lang="scss">
</style>

