<template>
  <div class="uri-form">
    <!-- Toggle auto-génération -->
    <div v-if="!editMode" class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        :id="id"
        v-model="uriGenerated"
      />
      <label class="form-check-label" :for="id">
        <opensilex-FormInputLabelHelper
          :label="label"
          :helpMessage="helpMessage"
          :labelFor="'field' + id"
        />
      </label>
    </div>

    <!-- Label en mode édition -->
    <div v-else>
      <opensilex-FormInputLabelHelper
        :label="label"
        :helpMessage="helpMessage"
        :labelFor="'field' + id"
        class="form-label"
      />
    </div>

    <!-- Champ URI -->
    <div>
      <input
        :id="'field' + id"
        v-model="uri"
        :disabled="editMode || uriGenerated"
        type="text"
        class="form-control"
        :class="{ 'is-invalid': !!errorMessage }"
        :placeholder="t('component.common.autogenerated-uri')"
      />
      <div v-if="errorMessage" class="invalid-feedback d-block">
        {{ errorMessage }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, inject, computed } from 'vue'
import { useField, defineRule, configure } from 'vee-validate'
import { url as urlRule } from '@vee-validate/rules'
import { useI18n } from 'vue-i18n'
import type OpenSilexVuePlugin from '../../../models/OpenSilexVuePlugin'

/** Props / Emits */
const props = defineProps<{
  uri?: string
  generated?: boolean
  editMode?: boolean
  label?: string
  helpMessage?: string
}>()

const emit = defineEmits<{
  (e: 'update:uri', v: string | undefined): void
  (e: 'update:generated', v: boolean): void
}>()

const { t } = useI18n()

/** ID */
const opensilex = inject<OpenSilexVuePlugin>('opensilex')
const id = ref('')
onMounted(() => {
  id.value = opensilex?.generateID?.() ?? Math.random().toString(36).slice(2)
})

/** État auto-générée */
const uriGenerated = ref(!!props.generated)

// règle URL de vee-validate
defineRule('url', urlRule)

// règle 'required' — si generated=true ->  pas requis, sinon requis
defineRule('required_if', (value: string, [generated]: any[]) => {
  const isGenerated = String(generated) === 'true'
  if (isGenerated) return true
  return !!value?.trim() || false
})

configure({
  generateMessage: (context) => {
    // context.rule?.name: 'required_if' ou 'url'
    // context.field: libellé lisible du champ
    return t(`validations.${context.rule?.name}`, { _field_: context.field })
  }
})

/** Règles dynamiques (réévaluées quand on (dé)coche) */
const rules = computed(() =>
  `${uriGenerated.value ? 'required_if:true' : 'required_if:false'}|url`
)

/** Champ + validation */
const fieldLabel = computed(() => (props.label ? t(props.label) : 'URI'))

const { value: uri, errorMessage, validate } = useField<string | undefined>(
  'uri',
  rules, // règles dynamiques (string réactif)
  {
    label: fieldLabel.value, //  pour {_field_} dans les messages
    initialValue: props.uri
  }
)
// parent -> child
watch(() => props.uri, (v) => {
  uri.value = typeof v === 'string' ? v : undefined
  validate()
})

watch(() => props.generated, (v) => {
  uriGenerated.value = !!v
  validate()
})

// child -> parent
watch(uri, (v) => {
  emit('update:uri', typeof v === 'string' && v.trim().length ? v : undefined)
})

watch(uriGenerated, (v) => {
  emit('update:generated', v)
  validate()
})

 // En mode édition, on force l'URI désactivée (sécurité UX)
 watch(() => props.editMode, (isEdit) => {
   if (isEdit) uriGenerated.value = true
 })
</script>

<style scoped lang="scss">
.uri-form {
  width: 100%;
}
</style>
