<template>
  <b-form-group :required="!uriGenerated">
    <ValidationProvider :vid="id">
      <b-form-checkbox v-if="!editMode" :id="id" v-model="uriGenerated" :name="id">
        <opensilex-FormInputLabelHelper
                :label="label"
                :helpMessage="helpMessage"
                :labelFor="'field' + id">
        </opensilex-FormInputLabelHelper>
        <!-- helpMessage="component.common.uri.help-message" -->
      </b-form-checkbox>
      <opensilex-FormInputLabelHelper
              v-else
              :label="label"
              :helpMessage="helpMessage"
              :labelFor="'field' + id"
              class="checkbox">

      </opensilex-FormInputLabelHelper>
    </ValidationProvider>
    <ValidationProvider
      :name="$t(label)"
      :rules="'required_if:' + id + ',false|url'"
      v-slot="{ errors }"
    >
      <div v-bind:class="{ errors: errors.length > 0 }">
        <b-form-input
          :id="'field' + id"
          v-model="valueURI"
          :disabled="uriGenerated"
          type="text"
          required
          :placeholder="$t('component.common.autogenerated-uri')"
        ></b-form-input>
      </div>
      <div class="error-message alert alert-danger">{{ errors[0] }}</div>
    </ValidationProvider>
  </b-form-group>
</template>

<script lang="ts">
import {
  Component,
  Prop,
  Model,
  Provide,
  PropSync
} from "vue-property-decorator";
import Vue from "vue";

@Component
export default class UriForm extends Vue {
  $opensilex: any;

  @PropSync("uri")
  valueURI: string;

  @Prop()
  editMode: boolean;

  @Prop()
  label;

  @Prop()
  helpMessage: string;

  @PropSync("generated")
  uriGenerated;

  id: string;

  created() {
    this.id = this.$opensilex.generateID();
  }
}
</script>

<style scoped lang="scss"> 
</style>

