<template>
  <b-modal ref="modalRef" @ok.prevent="validate" size="xl" :static="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <ValidationObserver ref="validatorRef">
      <b-form>
        <!-- URI -->
        <b-form-group :label="$t('component.group.group-uri') + ':'" label-for="uri">
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox
              v-if="!editMode"
              id="autogenerated"
              v-model="uriGenerated"
              name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider
            name="uri"
            rules="required_if:autogenerated,false|url"
            v-slot="{ errors }"
          >
            <b-form-input
              id="uri"
              v-model="form.uri"
              :disabled="uriGenerated"
              type="text"
              required
              :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Name -->
        <b-form-group :label="$t('component.common.name') + ':'" label-for="name" required>
          <ValidationProvider
            :name="$t('component.common.name')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-input
              id="name"
              v-model="form.name"
              type="text"
              required
              :placeholder="$t('component.group.form-name-placeholder')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Description -->

        <b-form-group
          :label="$t('component.common.description') + ':'"
          label-for="description"
          required
        >
          <ValidationProvider
            :name="$t('component.common.description')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-textarea
              id="description"
              v-model="form.description"
              required
              :placeholder="$t('component.group.form-description-placeholder')"
              autocomplete="no"
              rows="3"
            ></b-form-textarea>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <opensilex-GroupUserProfileForm ref="userProfilesRef" :userProfiles="form.userProfiles"></opensilex-GroupUserProfileForm>
      </b-form>
    </ValidationObserver>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import {
  UserCreationDTO,
  GroupUpdateDTO,
  SecurityService,
  UserGetDTO,
  ProfileGetDTO,
  GroupUserProfileModificationDTO
} from "opensilex-security/index";
import HttpResponse, { OpenSilexResponse } from "../../lib/HttpResponse";
import GroupUserProfileForm from "./GroupUserProfileForm.vue";
import { BvModal } from "bootstrap-vue";

@Component
export default class GroupForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;

  service: SecurityService;

  @Ref("userProfilesRef") readonly userProfilesRef!: GroupUserProfileForm;

  @Ref("modalRef") readonly modalRef!: any;

  @Ref("validatorRef") readonly validatorRef!: any;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  form: GroupUpdateDTO = {
    uri: "",
    name: "",
    description: "",
    userProfiles: []
  };

  title = "";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      name: "",
      description: "",
      userProfiles: []
    };
    this.userProfilesRef.clearForm();
  }

  created() {
    this.service = this.$opensilex.getService("opensilex.SecurityService");
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = this.$t("component.group.add").toString();
    this.uriGenerated = true;
    this.validatorRef.reset();
    this.modalRef.show();
  }

  showEditForm(form: GroupUpdateDTO) {
    this.clearForm();
    Object.keys(this.form).forEach(v => {
      this.form[v] = form[v];
    });
    this.userProfilesRef.initFormProfiles(form.userProfiles);
    this.editMode = true;
    this.title = this.$t("component.group.update").toString();
    this.uriGenerated = true;
    this.validatorRef.reset();
    this.modalRef.show();
  }

  hideForm() {
    this.modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    this.validatorRef.validate().then(isValid => {
      if (isValid) {
        if (this.uriGenerated && !this.editMode) {
          this.form.uri = null;
        }

        this.onValidate()
          .then(() => {
            this.$nextTick(() => {
              this.modalRef.hide();
            });
          })
          .catch(error => {
            if (error.status == 409) {
              console.error("Group already exists", error);
              this.$opensilex.errorHandler(
                error,
                this.$i18n.t("component.group.errors.group-already-exists")
              );
            } else {
              this.$opensilex.errorHandler(error);
            }
          });
      }
    });
  }
}
</script>

<style scoped lang="scss">
</style>

