<template>
  <b-modal ref="modalRef" @ok.prevent="validate" size="xl">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <b-form ref="formRef">
      <b-form-group :label="$t('component.group.group-uri') + ':'" label-for="uri">
        <b-form-checkbox
          v-if="!editMode"
          id="autogenerated"
          v-model="uriGenerated"
          name="autogenerated"
        >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
        <b-form-input
          id="uri"
          v-model="form.uri"
          :disabled="uriGenerated"
          type="text"
          required
          :placeholder="$t('component.common.autogenerated-uri')"
        ></b-form-input>
      </b-form-group>
      <b-form-group :label="$t('component.common.name') + ':'" label-for="name" required>
        <b-form-input
          id="name"
          v-model="form.name"
          type="text"
          required
          :placeholder="$t('component.group.form-name-placeholder')"
        ></b-form-input>
      </b-form-group>
      <b-form-group
        :label="$t('component.common.description') + ':'"
        label-for="description"
        required
      >
        <b-form-textarea
          id="description"
          v-model="form.description"
          required
          :placeholder="$t('component.group.form-description-placeholder')"
          autocomplete="no"
          rows="3"
        ></b-form-textarea>
      </b-form-group>
      <b-input-group class="mt-3 mb-3" size="sm">
        <b-input-group>
          <b-form-input
            v-model="filterPattern"
            debounce="300"
            :placeholder="$t('component.user.filter-placeholder')"
          ></b-form-input>
          <template v-slot:append>
            <b-btn :disabled="!filterPattern" variant="primary" @click="filterPattern = ''">
              <font-awesome-icon icon="times" size="sm" />
            </b-btn>
          </template>
        </b-input-group>
      </b-input-group>
      <div class="tables">
        <div class="table-left">
          <div>
            <div class="table-title">{{$t('component.group.form-all-users-title')}}</div>
            <b-table
              ref="tableRef"
              striped
              hover
              small
              :items="loadData"
              :fields="fields"
              :sort-by.sync="sortBy"
              :sort-desc.sync="sortDesc"
              no-provider-paging
            >
              <template v-slot:head(firstName)="data">{{ $t(data.label) }}</template>

              <template v-slot:cell(selected)="data">
                <b-form-checkbox
                  v-model="selectedUsersId[data.item.uri]"
                  @change="toggleUserSelection(data.item)"
                ></b-form-checkbox>
              </template>

              <template v-slot:cell(firstName)="data">
                {{data.item.firstName}} {{data.item.lastName}}
                <a
                  :href="'mailto:' + data.item.email"
                >({{ data.item.email }})</a>
              </template>
            </b-table>
          </div>
          <b-pagination
            class="bottom-pagination"
            v-model="currentPage"
            :total-rows="totalRow"
            :per-page="pageSize"
            @change="refresh()"
          ></b-pagination>
        </div>
        <div class="table-right">
          <div>
            <div
              class="table-title"
            >{{$t('component.group.form-selected-users-title')}} ({{selectedUsers.length}})</div>
            <b-table
              id="user-selection-table"
              striped
              hover
              small
              :items="selectedUsers"
              :fields="selectedFields"
              :per-page="pageSize"
              :current-page="currentSelectedPage"
            >
              <template v-slot:head(firstName)="data">{{ $t(data.label) }}</template>
              <template v-slot:head(admin)="data">{{ $t(data.label) }}</template>

              <template v-slot:cell(selected)="data">
                <b-form-checkbox
                  v-model="selectedUsersId[data.item.uri]"
                  :per-page="pageSize"
                  :current-page="currentSelectedPage"
                  @change="toggleUserSelection(data.item)"
                ></b-form-checkbox>
              </template>

              <template v-slot:cell(firstName)="data">
                {{data.item.firstName}} {{data.item.lastName}}
                <a
                  :href="'mailto:' + data.item.email"
                >({{ data.item.email }})</a>
              </template>

              <template v-slot:cell(uri)="data">
                <a class="uri-info">
                  <small>{{ data.item.uri }}</small>
                </a>
              </template>

              <template v-slot:cell(admin)="data">
                <b-form-select
                  size="sm"
                  value-field="uri"
                  text-field="name"
                  :options="profiles"
                  v-model="data.item.profile"
                  :required="true"
                  class="profile-selector"
                ></b-form-select>
              </template>
            </b-table>
          </div>
          <b-pagination
            class="bottom-pagination"
            v-model="currentSelectedPage"
            :total-rows="selectedUsers.length"
            :per-page="pageSize"
            aria-controls="user-selection-table"
          ></b-pagination>
        </div>
      </div>
    </b-form>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import {
  UserCreationDTO,
  GroupUpdateDTO,
  UsersService,
  UserGetDTO,
  ProfileGetDTO,
  GroupUserProfileModificationDTO
} from "opensilex-rest/index";
import HttpResponse, { OpenSilexResponse } from "../../lib/HttpResponse";

@Component
export default class GroupForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;

  @Prop()
  profiles: Array<ProfileGetDTO>;

  service: UsersService;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  form: GroupUpdateDTO = {
    uri: "",
    name: "",
    description: "",
    userProfiles: []
  };

  title = "";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      name: "",
      description: "",
      userProfiles: []
    };
    this.currentSelectedPage = 1;
    this.currentPage = 1;
    this.pageSize = 5;
    this.totalRow = 0;
    this.sortBy = "firstName";
    this.sortDesc = false;
    this.selectedUsersId = {};
    this.selectedUsers = [];
    this.filterPatternValue = "";
  }

  refresh() {
    let tableRef: any = this.$refs.tableRef;
    tableRef.refresh();
  }

  currentPage: number = 1;
  currentSelectedPage: number = 1;
  pageSize = 5;
  totalRow = 0;
  sortBy = "firstName";
  sortDesc = false;

  selectedUsersId: any = {};
  selectedUsers: any = [];

  private filterPatternValue: any = "";
  set filterPattern(value: string) {
    this.filterPatternValue = value;
    this.refresh();
  }

  get filterPattern() {
    return this.filterPatternValue;
  }

  created() {
    this.service = this.$opensilex.getService("opensilex.UsersService");
  }

  loadData() {
    let orderBy = [];
    if (this.sortBy) {
      let orderByText = this.sortBy + "=";
      if (this.sortDesc) {
        orderBy.push(orderByText + "desc");
      } else {
        orderBy.push(orderByText + "asc");
      }
    }

    return this.service
      .searchUsers(
        this.user.getAuthorizationHeader(),
        this.filterPattern,
        orderBy,
        this.currentPage - 1,
        this.pageSize
      )
      .then((http: HttpResponse<OpenSilexResponse<Array<UserGetDTO>>>) => {
        this.totalRow = http.response.metadata.pagination.totalCount;
        this.pageSize = http.response.metadata.pagination.pageSize;
        setTimeout(() => {
          this.currentPage = http.response.metadata.pagination.currentPage + 1;
        }, 0);

        return http.response.result;
      })
      .catch(this.$opensilex.errorHandler);
  }

  fields = [
    {
      key: "selected",
      label: ""
    },
    {
      key: "firstName",
      label: "component.common.name",
      sortable: true
    }
  ];

  selectedFields = [
    {
      key: "selected",
      label: ""
    },
    {
      key: "firstName",
      label: "component.common.name",
      sortable: true
    },
    {
      key: "admin",
      label: "component.profile.label"
    }
  ];

  toggleUserSelection(user) {
    if (!this.selectedUsersId[user.uri]) {
      if (this.profiles.length > 0) {
        user.profile = this.profiles[0].uri;
      }
      this.selectedUsers.push(user);

    } else {
      this.selectedUsers = this.selectedUsers.filter(element => {
        return element.uri != user.uri;
      });
      delete this.selectedUsersId[user.uri];
    }
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = this.$t("component.group.add").toString();
    this.uriGenerated = true;
    this.selectedUsers = [];
    this.selectedUsersId = {};
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  showEditForm(form: GroupUpdateDTO) {
    this.form = form;
    this.editMode = true;
    this.title = this.$t("component.group.update").toString();
    this.uriGenerated = true;

    this.selectedUsers = [];
    this.selectedUsersId = {};

    let userURIs = [];
    let profileByUser = {};
    form.userProfiles.forEach(groupUserProfile => {
      userURIs.push(groupUserProfile.userURI);
      profileByUser[groupUserProfile.userURI] = groupUserProfile.profileURI;
    });
    this.service
      .getUsersByURI(this.user.getAuthorizationHeader(), userURIs)
      .then((http: HttpResponse<OpenSilexResponse<Array<UserGetDTO>>>) => {
        let users = http.response.result;
        users.forEach((user: any) => {
          this.selectedUsersId[user.uri] = true;
          user.profile = profileByUser[user.uri];
          this.selectedUsers.push(user);
        });
      })
      .catch(this.$opensilex.errorHandler);
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    let formRef: any = this.$refs.formRef;
    if (formRef.checkValidity()) {
      if (this.uriGenerated && !this.editMode) {
        this.form.uri = null;
      }

      let userProfiles = [];
      console.log(this.selectedUsers);
      for (let i in this.selectedUsers) {
        let userProfile = this.selectedUsers[i];
        let userProfileDTO: GroupUserProfileModificationDTO = {
          profileURI: userProfile.profile,
          userURI: userProfile.uri
        };

        userProfiles.push(userProfileDTO);
      }

      this.form.userProfiles = userProfiles;

      this.onValidate()
        .then(() => {
          this.$nextTick(() => {
            let modalRef: any = this.$refs.modalRef;
            modalRef.hide();
          });
        })
        .catch(error => {
          if (error.status == 409) {
            // TODO display error message group already exists
            console.error("TODO display error message user already exists");
          } else {
            this.$opensilex.errorHandler(error);
          }
        });
    } else {
      // TODO validation error management
      console.error("TODO validation error management");
    }
  }
}
</script>

<style scoped lang="scss">
.tables {
  display: flex;
}

.table-left,
.table-right {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.table-left > div:first-child,
.table-right > div:first-child {
  flex: 1;
  flex-direction: column;
  flex-grow: 1;
}

.table-left {
  margin-right: 5px;
}

.table-right {
  margin-left: 5px;
}

.profile-selector {
  height: 20px;
  line-height: 15px;
  padding-top: 0;
  padding-bottom: 0;
}

.table-title {
  font-weight: bold;
  text-align: center;
}
</style>

