<template>
  <b-modal ref="modalRef" @ok.prevent="validate" size="xl">
    <template v-slot:modal-title>{{title}}</template>
    <b-form ref="formRef">
      <b-form-group label="Profile URI:" label-for="uri">
        <b-form-checkbox
          v-if="!editMode"
          id="autogenerated"
          v-model="uriGenerated"
          name="autogenerated"
        >Auto-generate URI</b-form-checkbox>
        <b-form-input
          id="uri"
          v-model="form.uri"
          :disabled="uriGenerated"
          type="text"
          required
          placeholder="Auto-generated URI"
        ></b-form-input>
      </b-form-group>
      <b-form-group label="Name:" label-for="name" required>
        <b-form-input
          id="name"
          v-model="form.name"
          type="text"
          required
          placeholder="Enter name"
          autocomplete="no"
        ></b-form-input>
      </b-form-group>

      <b-card no-body>
        <b-tabs pills card>
          <b-tab
            v-for="credentialsGroup in credentialsGroups"
            v-bind:key="credentialsGroup.groupId"
            v-bind:title="$t(credentialsGroup.groupKeyLabel)"
          >
            <b-form-checkbox-group
              v-bind:key="credentialsGroup.groupId"
              v-model="selectedCredentials[credentialsGroup.groupId]"
              v-bind:options="credentialOptions[credentialsGroup.groupId]"
              switches
            ></b-form-checkbox-group>
          </b-tab>
        </b-tabs>
      </b-card>
    </b-form>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import {
  ProfileGetDTO,
  CredentialsGroupDTO,
  ProfileCreationDTO
} from "opensilex-rest/index";

@Component
export default class ProfileForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  @Prop()
  credentialsGroups: any;

  private _selectedCredentials = null;

  get selectedCredentials() {
    let def: any = {};
    let credentialsGroups = this.credentialsGroups;
    for (let i = 0; i < credentialsGroups.length; i++) {
      def[credentialsGroups[i].groupId] = [];

      for (let j = 0; j < credentialsGroups[i].credentials.length; j++) {
        let credentialId = credentialsGroups[i].credentials[j].id;
        if (this.form.credentials.indexOf(credentialId) >= 0) {
          def[credentialsGroups[i].groupId].push(credentialId);
        }
      }
    }

    this._selectedCredentials = def;

    return this._selectedCredentials;
  }

  set selectedCredentials(value) {
    this._selectedCredentials = value;
  }

  get credentialOptions() {
    let credentialsGroups = this.credentialsGroups;
    let def: any = {};
    for (let i = 0; i < credentialsGroups.length; i++) {
      def[credentialsGroups[i].groupId] = [];

      for (let j = 0; j < credentialsGroups[i].credentials.length; j++) {
        let credential = credentialsGroups[i].credentials[j];
        def[credentialsGroups[i].groupId].push({
          text: this.$t(credential.label),
          value: credential.id
        });
      }
    }

    return def;
  }

  form: ProfileGetDTO = {
    uri: "",
    name: "",
    credentials: []
  };

  title = "Add profile";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      name: "",
      credentials: []
    };
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = "Add profile";
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  showEditForm(form: ProfileGetDTO) {
    this.form = form;
    this.editMode = true;
    this.title = "Update profile";
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  onValidate() {
    let credentials = [];
    for (let i in this._selectedCredentials) {
      credentials = credentials.concat(this._selectedCredentials[i]);
    }
    this.form.credentials = credentials;

    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    let formRef: any = this.$refs.formRef;
    if (formRef.checkValidity()) {
      if (this.uriGenerated && !this.editMode) {
        this.form.uri = null;
      }

      this.onValidate()
        .then(() => {
          this.$nextTick(() => {
            let modalRef: any = this.$refs.modalRef;
            modalRef.hide();
          });
        })
        .catch(error => {
          if (error.status == 409) {
            // TODO display error message profile already exists
            console.error("TODO display error message profile already exists");
          } else {
            this.$opensilex.errorHandler(error);
          }
        });
    } else {
      // TODO validation error management
      console.error("TODO validation error management");
    }
  }
}
</script>

<style scoped lang="scss">
</style>

