<template>
  <b-modal ref="modalRef" @ok.prevent="validate">
    <template v-slot:modal-title>{{title}}</template>
    <b-form ref="formRef">
      <b-form-group label="Profile URI:" label-for="uri">
        <b-form-checkbox
          v-if="!editMode"
          id="autogenerated"
          v-model="uriGenerated"
          name="autogenerated"
        >Auto-generate URI</b-form-checkbox>
        <b-form-input
          id="uri"
          v-model="form.uri"
          :disabled="uriGenerated"
          type="text"
          required
          placeholder="Auto-generated URI"
        ></b-form-input>
      </b-form-group>
      <b-form-group label="Name:" label-for="name" required>
        <b-form-input
          id="name"
          v-model="form.name"
          type="text"
          required
          placeholder="Enter name"
          autocomplete="no"
        ></b-form-input>
      </b-form-group>
      <b-form-group
        v-for="credentialsGroup in credentialsGroups"
        v-bind:key="credentialsGroup.groupId"
        :label="credentialsGroup.groupId"
        :label-for="credentialsGroup.groupId"
      >
      ????
        <b-form-checkbox-group
          v-for="credential in credentialsGroup.credentials"
          v-bind:key="credential.id"
          v-model="selectedCredentialsGroups[credentialsGroup.groupId]"
          :options="credentialOptions[credentialsGroup.groupId]"
          switches
        ></b-form-checkbox-group>
      </b-form-group>
    </b-form>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import {
  UserCreationDTO,
  ProfileGetDTO,
  CredentialsGroupDTO
} from "opensilex-rest/index";

@Component
export default class UserForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  selectedCredentialsGroups: any;
  credentialOptions: any;
  allCredentialsGroups: Array<CredentialsGroupDTO>;

  set credentialsGroups(allCredentialsGroups: Array<CredentialsGroupDTO>) {
    console.warn("!!!!!!!!!!", this.allCredentialsGroups, this.selectedCredentialsGroups, this.credentialOptions)
    this.allCredentialsGroups = allCredentialsGroups;
    this.selectedCredentialsGroups = this.getSelectedCredentials();
    this.credentialOptions = this.getCredentialOptions();
    console.warn("!!!!!!!!!!", this.allCredentialsGroups, this.selectedCredentialsGroups, this.credentialOptions)
  }

  get credentialsGroups() {
    return this.allCredentialsGroups;
  }

  getSelectedCredentials() {
    let def: any = {};
    for (let i in this.credentialsGroups) {
      def[this.credentialsGroups[i].groupId] = [];
    }

    return def;
  }

  getCredentialOptions() {
    let def: any = {};
    for (let i in this.credentialsGroups) {
      def[this.credentialsGroups[i].groupId] = [];
      for (let j in this.credentialsGroups[i].credentials) {
        let credential = this.credentialsGroups[i].credentials[j];
        def[this.credentialsGroups[i].groupId].push({
          text: credential.label,
          value: credential.id
        });
      }
    }

    return def;
  }

  form: ProfileGetDTO = {
    uri: "",
    name: "",
    credentials: []
  };

  title = "Add profile";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      name: "",
      credentials: []
    };
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = "Add profile";
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  showEditForm(form: UserCreationDTO) {
    this.form = form;
    this.editMode = true;
    this.title = "Update profile";
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    let formRef: any = this.$refs.formRef;
    if (formRef.checkValidity()) {
      if (this.uriGenerated && !this.editMode) {
        this.form.uri = null;
      }

      this.onValidate()
        .then(() => {
          this.$nextTick(() => {
            let modalRef: any = this.$refs.modalRef;
            modalRef.hide();
          });
        })
        .catch(error => {
          if (error.status == 409) {
            // TODO display error message user already exists
            console.error("TODO display error message user already exists");
          } else {
            this.$opensilex.errorHandler(error);
          }
        });
    } else {
      // TODO validation error management
      console.error("TODO validation error management");
    }
  }
}
</script>

<style scoped lang="scss">
</style>

