<template>
  <div>
    <opensilex-OntologyCsvImporter
      ref="importForm"
      :baseType="$opensilex.Oeso.DEVICE_TYPE_URI"
      :validateCSV="validateCSV"
      :uploadCSV="uploadCSV"
      :title="t('DeviceCsvForm.import-title')"
      :successImportMsg="t('DeviceCsvForm.successImportMsg')"
      @csvImported="onCsvImported"
    >
      <template #icon>
        <opensilex-Icon icon="bi#bi-bullseye" class="icon-title" />
      </template>

      <template #help>
        <opensilex-DeviceImportHelp />
      </template>

      <template #generator>
        <div class="col-12 col-md-2">
          <opensilex-Button
            class="me-2 greenThemeColor"
            :small="false"
            icon
            :label="t('DeviceCsvForm.generate-template')"
            @click="showTemplateGenerator"
          />

          <opensilex-OntologyCsvTemplateGenerator
            ref="templateGenerator"
            :baseType="$opensilex.Oeso.DEVICE_TYPE_URI"
            templatePrefix="device"
            :typePlaceholder="t('DeviceCsvForm.rdfTypes-placeholder')"
            :uriHelp="t('DeviceCsvForm.uri-help')"
            :uriExample="t('DeviceCsvForm.uri-example')"
            :typeHelp="t('DeviceCsvForm.type-help')"
            :typeExample="t('DeviceCsvForm.type-example')"
          />
        </div>
      </template>
    </opensilex-OntologyCsvImporter>
  </div>
</template>

<script setup lang="ts">
import { inject, ref } from 'vue'
import type OpenSilexVuePlugin from '@/models/OpenSilexVuePlugin'
import { useI18n } from 'vue-i18n'

const emit = defineEmits<{
  (e: 'csvImported', response: any): void
}>()

const $opensilex = inject<OpenSilexVuePlugin>('$opensilex')!
const { t } = useI18n()

const templateGenerator = ref<any>(null)
const importForm = ref<any>(null)

function show() {
  importForm.value?.show?.()
}

function showTemplateGenerator() {
  templateGenerator.value?.show?.()
}

function validateCSV(csvFile: File) {
  return $opensilex.uploadFileToService(
    '/core/devices/import_validation',
    {
      description: {},
      file: csvFile
    },
    null,
    false
  )
}

function uploadCSV(validationToken: string, csvFile: File) {
  return $opensilex.uploadFileToService(
    '/core/devices/import',
    {
      description: {
        validationToken
      },
      file: csvFile
    },
    null,
    false
  )
}

function onCsvImported(response: any) {
  emit('csvImported', response)
}

defineExpose({
  show
})
</script>

<style scoped>
</style>

<i18n>
en:
  DeviceCsvForm:
    import-title: Import device(s)
    successImportMsg: device(s) imported
    uri-example: "http://opensilex.org/id/device/rasperry_pi_4B"
    uri-help: Device URI (autogenerated if empty)
    generate-template: Generate template
    rdfTypes-placeholder: Select a device type
    type-example: vocabulary:SensingDevice
    type-help: "URI of the device type"

fr:
  DeviceCsvForm:
    import-title: Importer des appareils
    successImportMsg: appareil(s) importé(s)
    uri-example: "http://opensilex.org/id/device/rasperry_pi_4B"
    uri-help: URI de l'équipement (auto-générée si vide)
    generate-template: Générer un gabarit
    rdfTypes-placeholder: Sélectionner un type d'appareil
    type-example: vocabulary:SensingDevice
    type-help: "URI du type d'équipement"
</i18n>