<template>
  <b-modal ref="modalRef" size="lg" hide-footer :static="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>
    <template v-slot:modal-title>
      <font-awesome-icon icon="sun" />
      {{title}}
    </template>
    <form-wizard
      @on-loading="setLoading"
      @on-error="handleErrorMessage"
      ref="factorCreateFormWizard"
      shape="square"
      color="#00a38d"
    >
      <div class="loader" v-if="this.loadingWizard"></div>
      <h2 slot="title"></h2>
      <tab-content
        v-bind:title="$t('component.factor.form-wizard.general-informations')"
        :before-change="checkBeforeSkosStep"
      >
        <ValidationObserver ref="validatorRef">
          <b-form>
            <!-- URI -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                label="component.factor.uri"
                helpMessage="component.factor.uri-help"
              ></opensilex-FormInputLabelHelper>
              <ValidationProvider vid="autogenerated">
                <b-form-checkbox
                  v-if="!editMode"
                  id="autogenerated"
                  v-model="uriGenerated"
                  name="autogenerated"
                >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
              </ValidationProvider>
              <ValidationProvider
                name="uri"
                rules="required_if:autogenerated,false|url"
                v-slot="{ errors }"
              >
                <b-form-input
                  id="uri"
                  v-model="form.uri"
                  :disabled="uriGenerated"
                  type="text"
                  required
                  :placeholder="$t('component.common.autogenerated-uri')"
                ></b-form-input>
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
            </b-form-group>
            <!-- Alias -->
            <b-form-group required>
              <opensilex-FormInputLabelHelper
                label="component.factor.alias"
                helpMessage="component.factor.alias-help"
              ></opensilex-FormInputLabelHelper>
              <ValidationProvider
                :name="$t('component.factor.alias')"
                rules="required"
                v-slot="{ errors }"
              >
                <b-form-input
                  id="alias"
                  v-model="form.alias"
                  type="text"
                  required
                  :placeholder="$t('component.factor.form-alias-placeholder')"
                ></b-form-input>
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
            </b-form-group>
            <!-- Comment -->
            <b-form-group required>
              <opensilex-FormInputLabelHelper
                label="component.factor.comment"
                helpMessage="component.factor.comment-help"
              ></opensilex-FormInputLabelHelper>
              <ValidationProvider
                :name="$t('component.factor.comment')"
                rules="required"
                v-slot="{ errors }"
              >
                <b-form-input
                  id="comment"
                  v-model="form.comment"
                  type="text"
                  required
                  :placeholder="$t('component.factor.form-comment-placeholder')"
                ></b-form-input>
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
            </b-form-group>
          </b-form>
        </ValidationObserver>
      </tab-content>
      <tab-content v-bind:title="$t('component.common.form-wizard.external-ontologies')">
        <opensilex-ExternalReferencesForm @onUpdateSkos="callUpdateSkosFactorService" :skosReferences="skosReferences"></opensilex-ExternalReferencesForm>
      </tab-content>
      <template slot="footer" slot-scope="props">
        <div class="wizard-footer-left">
          <wizard-button
            v-if="props.activeTabIndex > 0 && !props.isLastStep"
            @click.native="props.prevTab()"
            :style="props.fillButtonStyle"
          >{{$t('component.common.form-wizard.previous')}}</wizard-button>
        </div>
        <div class="wizard-footer-right">
          <wizard-button
            v-if="!props.isLastStep"
            @click.native="props.nextTab()"
            class="wizard-footer-right"
            :style="props.fillButtonStyle"
          >{{$t( editMode ? 'component.factor.update' : 'component.factor.add')}}</wizard-button>
          <wizard-button
            v-else
            class="wizard-footer-right finish-button"
            :style="props.fillButtonStyle"
          >{{props.isLastStep ? 'component.common.form-wizard.done' : 'component.common.form-wizard.next'}}</wizard-button>
        </div>
      </template>
    </form-wizard>
  </b-modal>
</template>

<script lang="ts">

// remove on loading on form wizard
// @on-loading="setLoading"

import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import { FactorCreationDTO } from "opensilex-core/index";

@Component
export default class FactorForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: any;
  $t: any;
  $i18n: any;

  loadingWizard: boolean = false;
  errorMsg: string = null;
  count: number = 0;

  skosReferences = {
    exactMatch: [],
    narrower: [],
    closeMatch: [],
    broader: []
  };

  get user() {
    return this.$store.state.user;
  }

  mounted() {
    console.log(this.$refs);
  }

  uriGenerated = true;

  form: FactorCreationDTO = {
    uri: null,
    alias: null,
    comment: null,
    exactMatch: [],
    closeMatch: [],
    broader: [],
    narrower: []
    // lang: "en-US"
  };

  title = "";

  editMode = false;

  setUri(uri: string) {
    this.form.uri = uri;
  }

  clearForm() {
    this.form = {
      uri: null,
      alias: null,
      comment: null,
      exactMatch: [],
      closeMatch: [],
      broader: [],
      narrower: []
      // lang: "en-US"
    };
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = this.$t("component.factor.add").toString();
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
    let factorCreateFormWizard: any = this.$refs.factorCreateFormWizard;
    factorCreateFormWizard.reset();
  }

  showEditForm(form: FactorCreationDTO) {
    console.log(form);
    this.form = form;
    this.editMode = true;
    this.title = this.$t("component.factor.update").toString();
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
    let factorCreateFormWizard: any = this.$refs.factorCreateFormWizard;
    factorCreateFormWizard.reset(); 
    factorCreateFormWizard.activateAll();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  callUpdateSkosFactorService(skosReferences, done) {
    this.form = { ...this.form, ...skosReferences };
    return this.onValidateData();
  }

  async onValidateData() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
            result.then(resolve => {
              this.setUri(resolve);
            });
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  getLoadingWizard() {
    return this.loadingWizard;
  }

  getErrorMsg() {
    return this.errorMsg;
  }

  setLoading(value: boolean) {
    this.loadingWizard = value;
  }

  handleErrorMessage(errorMsg: string) {
    this.errorMsg = errorMsg;
  }

  validateForm() {
    let validatorRef: any = this.$refs.validatorRef;
    return validatorRef.validate();
  }

  async checkBeforeSkosStep() {
    if(this.editMode){
      this.skosReferences = {
        exactMatch : this.form.exactMatch,
        broader : this.form.broader,
        narrower : this.form.narrower,
        closeMatch : this.form.closeMatch
      }
    }


    return new Promise((resolve, reject) => {
      setTimeout(() => {
        this.setLoading(true);
        this.validateForm().then(isValid => {
          if (isValid) {
            this.onValidateData()
              .then(() => {
                this.editMode = true;
                this.uriGenerated = true;
                this.title = this.$t("component.factor.update").toString();
                this
                resolve(true);
              })
              .catch(error => {
                if (error.status == 409) {
                  console.error("factorLevel already exists", error);
                  this.$opensilex.errorHandler(
                    error,
                    this.$i18n.t("component.factorLevel.errors.already-exists")
                  );
                } else {
                  this.$opensilex.errorHandler(error);
                }
              });
          } else {
            this.errorMsg = "component.common.errors.form-step-errors";
            reject();
          }
        });
        this.setLoading(false);
      }, 400);
    });
  }
}
</script>

<style scoped lang="scss">
span.error {
  color: #e74c3c;
  font-size: 20px;
  display: flex;
  justify-content: center;
}
/* This is a css loader. It's not related to vue-form-wizard */
.loader,
.loader:after {
  border-radius: 50%;
  width: 10em;
  height: 10em;
}
.loader {
  margin: 60px auto;
  font-size: 10px;
  position: relative;
  text-indent: -9999em;
  border-top: 1.1em solid rgba(255, 255, 255, 0.2);
  border-right: 1.1em solid rgba(255, 255, 255, 0.2);
  border-bottom: 1.1em solid rgba(255, 255, 255, 0.2);
  border-left: 1.1em solid #00a38d;
  -webkit-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
  -webkit-animation: load8 1.1s infinite linear;
  animation: load8 1.1s infinite linear;
}
@-webkit-keyframes load8 {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes load8 {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
</style>
