<template>
  <b-modal ref="modalRef" @ok.prevent="validate" v-show="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <ValidationObserver ref="validatorRef">
      <b-form>
        <!-- URI -->
        <b-form-group :label="$t('component.factorLevel.uri') + ':'" label-for="uri">
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox
              v-if="!editMode"
              id="autogenerated"
              v-model="uriGenerated"
              name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider
            name="uri"
            rules="required_if:autogenerated,false|url"
            v-slot="{ errors }"
          >
            <b-form-input
              id="uri"
              v-model="form.uri"
              :disabled="uriGenerated"
              type="text"
              required
              :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Alias -->
        <b-form-group :label="$t('component.factorLevel.alias') + ':'" label-for="alias" required>
          <ValidationProvider
            :name="$t('component.factorLevel.alias')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-input
              id="alias"
              v-model="form.alias"
              type="text"
              required
              :placeholder="$t('component.factorLevel.form-alias-placeholder')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- Comment -->
        <b-form-group
          :label="$t('component.factorLevel.comment') + ':'"
          label-for="comment"
          required
        >
          <ValidationProvider
            :name="$t('component.factorLevel.comment')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-input
              id="comment"
              v-model="form.comment"
              type="text"
              required
              :placeholder="$t('component.factorLevel.form-comment-placeholder')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
        <!-- hasFactor -->
        <b-form-group
          :label="$t('component.factorLevel.hasFactor') + ':'"
          label-for="hasFactor"
          required
        >
          <ValidationProvider
            :name="$t('component.factorLevel.hasFactor')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-input
              id="hasFactor"
              v-model="form.hasFactor"
              type="text"
              required
              :placeholder="$t('component.factor-selector-placeholder')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>
      </b-form>
    </ValidationObserver>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import { FactorLevelCreationDTO } from "../../lib/model/factorLevelCreationDTO";

@Component
export default class FactorLevelForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;
  $t: any;
  $i18n: any;

  get user() {
    return this.$store.state.user;
  }

  mounted() {
    console.log(this.$refs);
  }

  uriGenerated = true;

  form: FactorLevelCreationDTO = {
    uri: "",
    alias: "",
    comment: "",
    hasFactor: ""
    // lang: "en-US"
  };

  title = "";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      alias: "",
      comment: "",
      hasFactor: ""
      // lang: "en-US"
    };
  }

  showCreateForm() {
    this.clearForm();
    console.log(this.$refs);
    this.editMode = false;
    this.title = this.$t("component.factorLevel.add").toString();
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  showEditForm(form: FactorLevelCreationDTO) {
    this.form = form;
    this.editMode = true;
    this.title = this.$t("component.factorLevel.update").toString();
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    let validatorRef: any = this.$refs.validatorRef;
    validatorRef.validate().then(isValid => {
      if (isValid) {
        if (this.uriGenerated && !this.editMode) {
          this.form.uri = null;
        }

        this.onValidate()
          .then(() => {
            this.$nextTick(() => {
              let modalRef: any = this.$refs.modalRef;
              modalRef.hide();
            });
          })
          .catch(error => {
            if (error.status == 409) {
              console.error("factorLevel already exists", error);
              this.$opensilex.errorHandler(
                error,
                this.$i18n.t(
                  "component.factorLevel.errors.already-exists"
                )
              );
            } else {
              this.$opensilex.errorHandler(error);
            }
          });
      }
    });
  }
}
</script>

<style scoped lang="scss">
</style>

