<template>
  <ValidationObserver ref="validatorRef">
    <opensilex-Tutorial
        ref="tutorial"
        :steps="tutorialSteps"
        @onFinish="onTutorialFinishOrSkip"
        @onSkip="onTutorialFinishOrSkip"
    >
    </opensilex-Tutorial>
    <div class="row align-items-center">

      <div class="col-lg-6">

        <!-- URI -->
        <opensilex-UriForm
            class="v-step-uri"
            :uri.sync="formDto.uri"
            label="component.common.uri"
            :generated.sync="uriGenerated"
            :required="true"
            helpMessage="AgroportalEnrichFormPart.uri-help"
            :editMode="editMode"
        ></opensilex-UriForm>

        <!-- Name -->
        <opensilex-InputForm
            class="v-step-name"
            :value.sync="formDto.name"
            label="component.common.name"
            type="text"
            :required="true"
            :placeholder="props.namePlaceholder"
        ></opensilex-InputForm>

        <!-- Comment -->
        <opensilex-TextAreaForm
            class="v-step-description"
            :value.sync="formDto.description"
            label="component.common.description">
        </opensilex-TextAreaForm>
      </div>
    </div>
  </ValidationObserver>
</template>

<script lang="ts">
import {Component, Prop, PropSync, Ref} from "vue-property-decorator";
import Vue from "vue";
import {Tour} from "vue-tour";
import {BaseVariableCreationDTO} from "@/components/variables/form/VariableFormTypes";

@Component
export default class AgroportalEnrichFormPart extends Vue {
  $opensilex: any;

  uriGenerated = true;

  @Prop()
  editMode;

  errorMsg: String = "";

  @PropSync("form")
  formDto: BaseVariableCreationDTO;

  @Prop()
  props: {
    namePlaceholder: string,
    descriptionPlaceholder: string
  };

  private tutorialSteps = [
    {
      target: ".v-step-uri",
      header: {title: "TODO URI"},
      content:
          "TODO By default, the URI of the concept will be generated by OpenSilex. You can input a custom URI if you prefer.",
      params: {placement: "right"}
    },
    {
      target: ".v-step-name",
      header: {title: "TODO Name"},
      content: "TODO Enter the name of your concept.",
      params: {placement: "right"}
    },
    {
      target: ".v-step-description",
      header: {title: "TODO Description"},
      content: "TODO Enter the description of your concept.",
      params: {placement: "right"}
    },
    {
      target: "#v-step-wizard-buttons",
      header: {title: "TODO Validation"},
      content:
          `TODO Click on '${this.$t('component.common.form-wizard.next')}' to proceed to the next step, where you will add external references to your concept. Click on '${this.$t("AgroportalSearchFormPart.save")}' to save your concept as-is.`,
      params: {placement: "top"}
    },
  ];

  private savedFormBeforeTutorial: BaseVariableCreationDTO;

  @Ref("tutorial")
  private readonly tutorial: Tour;

  handleErrorMessage(errorMsg: string) {
    this.errorMsg = errorMsg;
  }

  @Ref("modalRef") readonly modalRef!: any;
  @Ref("validatorRef") readonly validatorRef!: any;

  reset() {
    this.uriGenerated = true;
    return this.validatorRef.reset();
  }

  validate() {
    return this.validatorRef.validate();
  }

  startTutorial() {
    this.savedFormBeforeTutorial = JSON.parse(JSON.stringify(this.formDto));
    this.formDto.name = this.$t(this.props.namePlaceholder).toString();
    this.formDto.description = this.$t(this.props.descriptionPlaceholder).toString();
    this.tutorial.start();
  }

  onTutorialFinishOrSkip() {
    this.formDto = JSON.parse(JSON.stringify(this.savedFormBeforeTutorial));
  }
}
</script>

<style scoped lang="scss">
a {
  color: #007bff;
}
</style>

<i18n>
en:
  AgroportalEnrichFormPart:
    uri-help: "Uncheck this checkbox if you want to insert a concept from an existing ontology or if want to set a particular URI. Let it checked if you want to create a new entity with an auto-generated URI"
fr:
  AgroportalEnrichFormPart:
    uri-help: "Décocher si vous souhaitez ajouter une entité à partir d'une ontologie existante ou si vous souhaitez spécifier une URI particulière. Laisser coché si vous souhaitez ajouter une entité avec une URI auto-générée"
</i18n>