<template>
  <b-modal ref="modalRef" size="lg" :static="true">
    <template v-slot:modal-title>
      <i>
        <font-awesome-icon icon="project-diagram" />
        {{title}}
      </i>
    </template>
    <ValidationObserver ref="validatorRef">
      <!-- URI -->
      <b-form>
        <form-wizard title subtitle ref="wizardRef" shape="square" color="#00a38d">
          <tab-content v-bind:title="$t('component.experiment.form-wizard.general-informations')">
            <b-form-group>
              <ValidationProvider vid="autogenerated">
                <b-form-checkbox
                  v-if="!editMode"
                  id="autogenerated"
                  v-model="uriGenerated"
                  name="autogenerated"
                >
                  <opensilex-FormInputLabelHelper
                    label="component.project.uri"
                    helpMessage="component.common.uri.help-message"
                    labelFor="uri"
                  ></opensilex-FormInputLabelHelper>
                </b-form-checkbox>
              </ValidationProvider>
              <ValidationProvider
                name="uri"
                rules="required_if:autogenerated,false|url"
                v-slot="{ errors }"
              >
                <b-form-input
                  id="uri"
                  v-model="form.uri"
                  :disabled="uriGenerated"
                  type="text"
                  required
                  :placeholder="$t('component.common.autogenerated-uri')"
                ></b-form-input>
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
            </b-form-group>

            <div class="row">
              <!-- Name -->
              <div class="col-md-6">
                <b-form-group required label-class="required">
                  <opensilex-FormInputLabelHelper
                    :label="$t('component.common.name')"
                    labelFor="name"
                  ></opensilex-FormInputLabelHelper>
                  <ValidationProvider
                    :name="$t('component.common.name')"
                    rules="required"
                    v-slot="{ errors }"
                  >
                    <b-form-input
                      id="name"
                      v-model="form.label"
                      type="text"
                      required
                      :placeholder="$t('component.project.form-name-placeholder')"
                    ></b-form-input>

                    <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                  </ValidationProvider>
                </b-form-group>
              </div>
              <!-- ShortName  -->
              <div class="col-md-6">
                <b-form-group>
                  <opensilex-FormInputLabelHelper
                    :label="$t('component.common.acronym')"
                    labelFor="staracronymtDate"
                  ></opensilex-FormInputLabelHelper>
                  <b-form-input
                    id="acronym"
                    v-model="form.shortname"
                    type="text"
                    :placeholder="$t('component.project.form-acronym-placeholder')"
                  ></b-form-input>
                </b-form-group>
              </div>
            </div>
            <div class="row">
              <!-- StartDate -->
              <div class="col-lg-6">
                <b-form-group required>
                  <opensilex-FormInputLabelHelper
                    :label="$t('component.experiment.startDate')"
                    labelFor="startDate"
                  ></opensilex-FormInputLabelHelper>
                  <ValidationProvider
                    :name="$t('component.experiment.startDate')"
                    rules="required"
                    v-slot="{ errors }"
                  >
                    <b-form-input
                      id="startDate"
                      v-model="form.startDate"
                      type="date"
                      value="2020-03-05"
                      required
                    ></b-form-input>
                    <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                  </ValidationProvider>
                </b-form-group>
              </div>
              <!-- EndDate -->
              <div class="col-lg-6">
                <b-form-group>
                  <opensilex-FormInputLabelHelper
                    :label="$t('component.experiment.endDate')"
                    labelFor="endDate"
                  ></opensilex-FormInputLabelHelper>
                  <ValidationProvider
                    :name="$t('component.experiment.endDate')"
                    v-slot="{ errors }"
                  >
                    <b-form-input
                      id="endDate"
                      v-model="form.endDate"
                      type="date"
                      value="2020-03-05"
                    ></b-form-input>
                    <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                  </ValidationProvider>
                </b-form-group>
              </div>
            </div>

            <!-- Objective -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                :label="$t('component.project.objective')"
                labelFor="objective"
              ></opensilex-FormInputLabelHelper>
              <b-form-input
                id="objective"
                v-model="form.objective"
                type="text"
                :placeholder="$t('component.project.form-objective-placeholder')"
              ></b-form-input>
            </b-form-group>

            <!-- Description -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                :label="$t('component.project.description')"
                labelFor="description"
              ></opensilex-FormInputLabelHelper>
              <b-form-textarea
                id="description"
                v-model="form.description"
                required
                :placeholder="$t('component.project.form-description-placeholder')"
                autocomplete="no"
                rows="3"
              ></b-form-textarea>
            </b-form-group>
          </tab-content>

          <tab-content v-bind:title="$t('component.experiment.form-wizard.infra-groups-projects')">
            <!-- Financial funding -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                :label="$t('component.project.financialFunding')"
                labelFor="financialFunding"
              ></opensilex-FormInputLabelHelper>
              <b-form-input
                id="financialFunding"
                v-model="form.hasFinancialFunding"
                type="text"
                :placeholder="$t('component.project.form-financialFunding-placeholder')"
              ></b-form-input>
            </b-form-group>

            <!--Coordinators -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                :label="$t('component.project.coordinators')"
                labelFor="coordinators"
              ></opensilex-FormInputLabelHelper>
              <opensilex-UserSelector
                ref="coordinatorsRef"
                id="coordinators"
                :selectedUsers="form.coordinators"
                @updateUsers="updateCoordinators"
              ></opensilex-UserSelector>
            </b-form-group>
            <!-- Scientific contacts -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                :label="$t('component.project.scientificContacts')"
                labelFor="scientificContacts"
              ></opensilex-FormInputLabelHelper>
              <opensilex-UserSelector
                ref="scientificContactsRef"
                id="scientificContacts"
                :selectedUsers="form.scientificContacts"
                @updateUsers="updateScientificContacts"
              ></opensilex-UserSelector>
            </b-form-group>
            <!-- Administrative contacts -->
            <b-form-group>
              <opensilex-FormInputLabelHelper
                :label="$t('component.project.administrativeContacts')"
                labelFor="administrativeContacts"
              ></opensilex-FormInputLabelHelper>
              <opensilex-UserSelector
                ref="administrativeContactsRef"
                id="administrativeContacts"
                :selectedUsers="form.administrativeContacts"
                @updateUsers="updateAdminContacts"
              ></opensilex-UserSelector>
            </b-form-group>
          </tab-content>

          <template slot="footer" slot-scope="props">
            <footer class="modal-footer modal-footer-replacement">
              <div class="wizard-footer-left">
                <b-button
                  variant="secondary"
                  @click="hideForm"
                >{{$t('component.common.form-wizard.cancel')}}</b-button>
              </div>

              <div class="wizard-footer-right">
                <b-button-group>
                  <b-button
                    variant="success"
                    v-if="props.activeTabIndex > 0"
                    @click="props.prevTab()"
                  >{{$t('component.common.form-wizard.previous')}}</b-button>
                  <b-button
                    v-if="!props.isLastStep"
                    variant="primary"
                    @click="validateStep(props)"
                  >{{$t('component.common.form-wizard.next')}}</b-button>
                  <b-button
                    v-if="props.isLastStep"
                    @click="validate"
                    variant="primary"
                  >{{$t('component.common.form-wizard.done')}}</b-button>
                </b-button-group>
              </div>
            </footer>
          </template>
        </form-wizard>
      </b-form>
    </ValidationObserver>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import { ProjectGetDTO } from "opensilex-core/index";
import { SecurityService, UserGetDTO } from "opensilex-security/index";
import HttpResponse, {
  OpenSilexResponse
} from "opensilex-security/HttpResponse";

@Component
export default class ProjectForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;
  $i18n: any;

  @Ref("modalRef") readonly modalRef!: any;
  @Ref("validatorRef") readonly validatorRef!: any;
  @Ref("wizardRef") readonly wizardRef!: any;

  @Ref("administrativeContactsRef") readonly administrativeContactsRef!: any;
  @Ref("scientificContactsRef") readonly scientificContactsRef!: any;
  @Ref("coordinatorsRef") readonly coordinatorsRef!: any;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;
  form: ProjectGetDTO = {
    uri: "",
    label: "",
    shortname: "",
    hasFinancialFunding: "",
    description: "",
    objective: "",
    startDate: "",
    endDate: "",
    keywords: [],
    homePage: "",
    experiments: [],
    administrativeContacts: [],
    coordinators: [],
    scientificContacts: [],
    relatedProjects: []
  };

  title = "";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      label: "",
      shortname: undefined,
      hasFinancialFunding: undefined,
      description: undefined,
      objective: undefined,
      startDate: "",
      endDate: undefined,
      keywords: undefined,
      homePage: undefined,
      experiments: undefined,
      administrativeContacts: [],
      coordinators: [],
      scientificContacts: [],
      relatedProjects: undefined
    };
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = this.$i18n.t("component.project.add").toString();
    this.uriGenerated = true;
    this.validatorRef.reset();
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
    this.administrativeContactsRef.selectUsers(
      this.form.administrativeContacts
    );
    this.scientificContactsRef.selectUsers(this.form.scientificContacts);
    this.coordinatorsRef.selectUsers(this.form.coordinators);
    this.wizardRef.reset();
  }

  showEditForm(form: ProjectGetDTO) {
    this.form = form;
    this.editMode = true;
    this.title = this.$i18n.t("component.project.update").toString();
    this.uriGenerated = true;
    this.validatorRef.reset();
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
    this.administrativeContactsRef.selectUsers(
      this.form.administrativeContacts
    );
    this.scientificContactsRef.selectUsers(this.form.scientificContacts);
    this.coordinatorsRef.selectUsers(this.form.coordinators);

    this.wizardRef.tabs.forEach(tab => {
      tab.checked = true;
    });
    this.wizardRef.navigateToTab(0);
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  updateAdminContacts(contacts) {
    this.form.administrativeContacts = contacts;
  }
  updateScientificContacts(contacts) {
    this.form.scientificContacts = contacts;
  }
  updateCoordinators(contacts) {
    this.form.coordinators = contacts;
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validateStep(props) {
    this.validatorRef.validate().then(isValid => {
      if (isValid) {
        props.nextTab();
      }
    });
  }

  validate() {
    this.validatorRef.validate().then(isValid => {
      if (isValid) {
        if (this.uriGenerated && !this.editMode) {
          this.form.uri = null;
        }

        this.onValidate()
          .then(() => {
            this.$nextTick(() => {
              this.modalRef.hide();
            });
          })
          .catch(error => {
            if (error.status == 409) {
              console.error("Project already exists", error);
              this.$opensilex.errorHandler(
                error,
                this.$i18n.t("component.group.errors.group-already-exists")
              );
            } else {
              this.$opensilex.errorHandler(error);
            }
          });
      }
    });
  }
}
</script>

<style scoped>
::v-deep .modal-body {
  padding-top: 0;
  padding-bottom: 0;
}

::v-deep .modal-footer {
  display: none;
}

::v-deep .wizard-header {
  display: none;
}

::v-deep .wizard-tab-content {
  padding-top: 5px;
}

.modal-footer-replacement {
  position: absolute;
  display: block;
  width: 100%;
  left: 0;
  bottom: 0;
}

::v-deep .vue-form-wizard {
  padding-bottom: 50px;
}
</style>

