<template>
  <b-modal ref="modalRef" @ok.prevent="validate" size="xl" :static="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <ValidationObserver ref="validatorRef">
      <!-- URI -->
      <b-form>
        <b-form-group :label="$t('component.project.uri') + ':'" label-for="uri">
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox
              v-if="!editMode"
              id="autogenerated"
              v-model="uriGenerated"
              name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider
            name="uri"
            rules="required_if:autogenerated,false|url"
            v-slot="{ errors }"
          >
            <b-form-input
              id="uri"
              v-model="form.uri"
              :disabled="uriGenerated"
              type="text"
              required
              :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Name -->
        <b-form-group
          :label="$t('component.project.name') + ':'"
          label-for="name"
          required
          label-class="required"
        >
          <ValidationProvider
            :name="$t('component.common.name')"
            rules="required"
            v-slot="{ errors }"
          >
            <b-form-input
              id="name"
              v-model="form.label"
              type="text"
              required
              :placeholder="$t('component.project.form-name-placeholder')"
            ></b-form-input>

            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Period -->
        <b-form inline>
          <label class="mr-sm-2 required" for="inline-form-custom-select-pref">Start Date</label>
          <b-input-group class="mt-3 mb-3" size="sm" id="inline-form-custom-select-pref">
            <ValidationProvider
              :name="$t('component.common.startDate')"
              rules="required"
              v-slot="{ errors }"
            >
              <datePicker
                v-model="form.startDate"
                input-class="form-control"
                placeholder="Select a date"
                :clear-button="true"
                @input="onStartDateSelected"
                @cleared="onStartDateCleared"
              ></datePicker>

              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
            </ValidationProvider>
          </b-input-group>

          <label class="mr-sm-2 ml-4 required" for="inline-2">End Date</label>
          <b-input-group class="mt-3 mb-3" size="sm" id="inline-2">
            <ValidationProvider
              :name="$t('component.common.endDate')"
              rules="required"
              v-slot="{ errors }"
            >
              <datePicker
                v-model="form.endDate"
                input-class="form-control"
                placeholder="Select a date"
                :clear-button="true"
                @input="onEndDateSelected"
                @cleared="onEndDateCleared"
              ></datePicker>
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
            </ValidationProvider>
          </b-input-group>
        </b-form>

        <!-- ShortName 
        <b-form-group :label="$t('component.common.acronym') + ':'" label-for="acronym">
          <b-form-input
            id="acronym"
            v-model="form.shortname"
            type="text"
            :placeholder="$t('component.project.form-comment-placeholder')"
          ></b-form-input>
        </b-form-group>
        
        -->

        <!-- Financial funding -->
        <b-form-group
          :label="$t('component.project.financialFunding') + ':'"
          label-for="financialFunding"
        >
          <b-form-input
            id="financialFunding"
            v-model="form.hasFinancialFunding"
            type="text"
            :placeholder="$t('component.project.form-financialFunding-placeholder')"
          ></b-form-input>
        </b-form-group>

        <!-- Description -->
        <b-form-group :label="$t('component.project.description') + ':'" label-for="description">
          <b-form-textarea
            id="description"
            v-model="form.description"
            required
            :placeholder="$t('component.project.form-description-placeholder')"
            autocomplete="no"
            rows="3"
          ></b-form-textarea>
        </b-form-group>
      </b-form>
    </ValidationObserver>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import { ProjectGetDTO } from "opensilex-core/index";

@Component
export default class ProjectForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;
  $i18n: any;

  @Ref("modalRef") readonly modalRef!: any;
  @Ref("validatorRef") readonly validatorRef!: any;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  form: ProjectGetDTO = {
    uri: "",
    label: "",
    shortname: "",
    hasFinancialFunding: "",
    description: "",
    objective: "",
    startDate: "",
    endDate: "",
    keywords: [],
    homePage: "",
    experiments: [],
    administrativeContacts: [],
    coordinators: [],
    scientificContacts: [],
    relatedProjects: []
  };

  title = "";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      label: "",
      shortname: undefined,
      hasFinancialFunding: undefined,
      description: undefined,
      objective: undefined,
      startDate: "",
      endDate: "",
      keywords: undefined,
      homePage: undefined,
      experiments: undefined,
      administrativeContacts: undefined,
      coordinators: undefined,
      scientificContacts: undefined,
      relatedProjects: undefined
    };
  }

  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = this.$i18n.t("component.project.add").toString();
    this.uriGenerated = true;

    this.validatorRef.reset();
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  showEditForm(form: ProjectGetDTO) {
    this.form = form;
    this.editMode = true;
    this.title = this.$i18n.t("component.project.update").toString();
    this.uriGenerated = true;
    this.validatorRef.reset();
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    this.validatorRef.validate().then(isValid => {
      if (isValid) {
        if (this.uriGenerated && !this.editMode) {
          this.form.uri = null;
        }

        this.onValidate()
          .then(() => {
            this.$nextTick(() => {
              this.modalRef.hide();
            });
          })
          .catch(error => {
            if (error.status == 409) {
              console.error("Project already exists", error);
              this.$opensilex.errorHandler(
                error,
                this.$i18n.t("component.group.errors.group-already-exists")
              );
            } else {
              this.$opensilex.errorHandler(error);
            }
          });
      }
    });
  }

  onStartDateSelected() {
    console.log("start date" + this.form.startDate);
    if (this.form.startDate !== null) {
      console.log("ici");
      this.form.startDate = this.format(this.form.startDate);
    }
  }

  onEndDateSelected() {
    console.log("end date" + this.form.endDate);
    if (this.form.endDate !== null) {
      this.form.endDate = this.format(this.form.endDate);
    }
  }

  onStartDateCleared() {
    console.log("start date cleared");
    this.form.startDate = "";
  }
  onEndDateCleared() {
    console.log("end date cleared");
    this.form.endDate = "";
  }

  format(date) {
    var d = new Date(date),
      month = "" + (d.getMonth() + 1),
      day = "" + d.getDate(),
      year = d.getFullYear();

    if (month.length < 2) month = "0" + month;
    if (day.length < 2) day = "0" + day;

    return [year, month, day].join("-");
  }
}
</script>

<style scoped>
div >>> label.required::after {
  content: " * ";
  color: red;
}
</style>

