ontologies:
    baseURI: http://www.phenome-fppn.fr/
    baseURIAlias: test
    sparql:
        config:
            serverURI: http://138.102.159.37:8080/rdf4j-server/
            repository: phis-test

file-system:
    fs:
        config:
            defaultFS: S3

            connections:
                S3:
                    implementation: org.opensilex.fs.s3.S3FileStorageConnection
                    config:
                        endpoint: https://s3.datacloud.helsinki.fi
                        region: eu-west-3
                        bucket: 2022-phis-test

big-data:
    mongodb:
        config:
            host: localhost
            port: 8668
            database: opensilex