system:
    ignoredModules:
        opensilex.service.PhisWsModule: opensilex-phis.jar
        opensilex.service.BrapiModule: opensilex-brapi.jar
        org.opensilex.opensilex-mobile.MobileModule: opensilex-mobile.jar
        org.opensilex.DataAnalysisModule : opensilex-data-analysis.jar

ontologies:
    baseURI: http://opensilex.dev/
    baseURIAlias: siduri
    sparql:
        #        implementation: org.opensilex.sparql.rdf4j.RDF4JInMemoryServiceFactory
        config:
            serverURI: http://localhost:8667/rdf4j-server/
            repository: opensilex

file-system:
    fs:
        config:
            defaultFS: local
            connections:
                local:
                    implementation: org.opensilex.fs.local.LocalFileSystemConnection
                    config:
                        basePath: ../../opensilex-data
                gridfs:
                    implementation: org.opensilex.fs.gridfs.GridFSConnection
                    config:
                        host: localhost
                        port: 8668
                        database: opensilex


big-data:
    mongodb:
        config:
            host: localhost
            port: 8668
            database: opensilex

phisws:
    infrastructure: opensilex
    
core:
    enableOntologyCaching: false
    metrics:
        enableMetrics: false
        system:
            timeBeforeFirstMetric: 1
            delayBetweenMetrics: 30
            metricsTimeUnit: DAYS
        experiments:
            timeBeforeFirstMetric: 1
            delayBetweenMetrics: 7
            metricsTimeUnit: DAYS


front:
    agroportal:
        entity:
            - AGROVOC
            - PO
        trait:
            - PATO
        method:
            - TRANSFORMON
        unit:
            - OBOE

    applicationName: Siduri

    theme: opensilex-siduri#siduri
    loginComponent: opensilex-siduri-SiduriLoginComponent
    footerComponent: opensilex-siduri-SiduriFooterComponent
    headerComponent: opensilex-siduri-SiduriHeaderComponent

data-analysis:
     scientificAppServer:
         config:
            enable: true
            host: localhost
            port: 8098
            #landingPage: /proxy
            #publicServerURL : http://localhost/proxy
            #serverServletContextPath : /proxy         
            # Docker container prefix name (multiple shinyproxy on same server) (String)
            shinyProxyContainerPrefix: siduri
            # Docker network name (String)
            shinyProxyNetwork: siduri-shiny-proxy-network

