ontologies:
    baseURI: http://phenome.inrae.fr/m3p/
    baseURIAlias: dev
    sparql:
        #        implementation: org.opensilex.sparql.rdf4j.RDF4JInMemoryServiceFactory
        config:
            serverURI: http://localhost:8667/rdf4j-server/
            repository: opensilex

file-system:
    fs:
        config:
            defaultFS: gridfs
            connections:
                gridfs:
                    implementation: org.opensilex.fs.gridfs.GridFSConnection
                    config:
                        host: localhost
                        port: 8668
                        database: opensilex

big-data:
    mongodb:
        config:
            host: localhost
            port: 8668
            database: opensilex
    #            timezone: Europe/Paris

phisws:
    infrastructure: opensilex

system:
    ignoredModules:
        org.opensilex.opensilex-mobile.MobileModule: opensilex-mobile.jar

front:
    connectAsGuest: true

security:
    gdprPdfPathsByLanguages:
        en: /home/roux/Documents/utile/configs/rgpd_en
        fr: /home/roux/Documents/utile/configs/rgpd_en

core :
    agroportal:
        basePath: "https://agroportal.eu"
        baseAPIPath: "https://data.agroportal.eu"
        externalAPIKey: "8bc3c0c9-464a-4bce-a218-a9d43fbf0df8"