<template>
  <b-form>
    <!-- URI -->
    <opensilex-UriForm
      :uri.sync="form.uri" 
      label="DeviceForm.uri"
      :editMode="editMode"
      :generated.sync="uriGenerated"
      helpMessage="DeviceForm.uri-help"
    ></opensilex-UriForm>

    <!-- rdfType -->
    <opensilex-TypeForm
      :type.sync="form.rdf_type"
      :baseType="$opensilex.Oeso.DEVICE_TYPE_URI"
      helpMessage="DeviceForm.type-help"    
      :required="true"
    ></opensilex-TypeForm>

    <!-- name -->
    <opensilex-InputForm
      :value.sync="form.name"
      label="DeviceForm.name"
      type="text"
      helpMessage="DeviceForm.name-help"
      :required="true"
    ></opensilex-InputForm>

    <!-- brand -->
    <opensilex-InputForm
      :value.sync="form.brand"
      label="DeviceForm.brand"
      type="text"
      helpMessage="DeviceForm.brand-help"
    ></opensilex-InputForm>

    <!-- constructor_model -->
    <opensilex-InputForm
      :value.sync="form.constructor_model"
      label="DeviceForm.constructor_model"
      type="text"
      helpMessage="DeviceForm.constructor_model-help"
    ></opensilex-InputForm>

    <!-- serial_number -->
    <opensilex-InputForm
      :value.sync="form.serial_number"
      label="DeviceForm.serial_number"
      type="number"
      helpMessage="DeviceForm.serial_number-help"
    ></opensilex-InputForm>

   <!--person_in_charge -->
    <opensilex-UserSelector
      :users.sync="form.person_in_charge"
      label="DeviceForm.person_in_charge"
      helpMessage="DeviceForm.person_in_charge-help"
    ></opensilex-UserSelector>

    <!-- start_up -->
    <opensilex-InputForm
      :value.sync="form.start_up"
      label="DeviceForm.start_up"
      type="date"
      helpMessage="DeviceForm.start_up-help"
    ></opensilex-InputForm>

    <!-- removal -->
    <opensilex-InputForm
      :value.sync="form.removal"
      label="DeviceForm.removal"
      type="date"
      helpMessage="DeviceForm.removal-help"
    ></opensilex-InputForm>

    <!-- description -->
    <opensilex-TextAreaForm
      :value.sync="form.description"
      label="DeviceForm.description"
      type="text"
      helpMessage="DeviceForm.description-help"
    ></opensilex-TextAreaForm>

  </b-form>
</template>

<script lang="ts">
import { Component, Prop, Ref, Watch } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import {DevicesService} from "opensilex-core/index"; 
import HttpResponse, { OpenSilexResponse } from "../../lib/HttpResponse";

@Component
export default class DeviceForm extends Vue {
  $opensilex: any;
  service: DevicesService;
  $store: any;
  $t: any;

  uriGenerated = true;

  get user() {
    return this.$store.state.user;
  } 

  @Prop()
  editMode;

  @Prop({
    default: () => {
      return {
        device: {
            uri: undefined,
            name: undefined,
            rdf_type: undefined,
            brand: undefined,
            constructor_model: undefined,
            serial_number: undefined,
            person_in_charge: undefined,
            start_up: undefined,
            removal: undefined,
            description: undefined
        }
      }
    }
  })
  form: any;

  reset() {
    this.uriGenerated = true;
  }

  update(form) {
    this.$opensilex
      .getService("opensilex.DevicesService")
      .updateDevice(form)
      .then((http: HttpResponse<OpenSilexResponse<any>>) => {
        let uri = http.response.result;
        console.debug("device updated", uri);
        this.$emit("onUpdate", form);
      })
      .catch(this.$opensilex.errorHandler);
  }

}
</script>

<style scoped lang="scss">
</style>

<i18n>

en:
  DeviceForm:
    uri: URI 
    uri-help: Unique device identifier autogenerated 
    type: Type
    type-help: Device Type
    name: Name
    name-help: A name given to the device
    brand: Brand
    brand-help:
    constructor_model: Constructor model
    constructor_model-help:
    serial_number: Serial number
    serial_number-help:
    person_in_charge: Person in charge
    person_in_charge-help:
    start_up: Start up
    start_up-help:
    removal: Removal
    removal-help:
    description: Description
    description-help:

fr:
  DeviceForm:
    uri: URI 
    uri-help: Identifiant unique du dispositif généré automatiquement 
    type: Type
    type-help: Type de dispositif 
    name: Nom
    name-help: Nom du dispositif 
    brand: Marque
    brand-help:
    constructor_model: Modèle constructeur
    constructor_model-help:
    serial_number: Numéro de série
    serial_number-help:
    person_in_charge: Personne responsable
    person_in_charge-help:
    start_up: Date d'obtention
    start_up-help:
    removal: Date de mise hors service
    removal-help:
    description: Description
    description-help:

</i18n>
