<template>
    <b-modal ref="modalRef" @ok.prevent="validate" size="lg" :static="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <ValidationObserver ref="validatorRef">

        <b-form>

        <!-- URI -->
        <b-form-group >
            <opensilex-FormInputLabelHelper label=component.variable.entity-uri helpMessage="component.variable.entity-uri-help"  ></opensilex-FormInputLabelHelper>
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox v-if="!editMode" id="autogenerated" v-model="uriGenerated"  name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}
            </b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider name="uri" rules="required_if:autogenerated,false|url" v-slot="{ errors }">
            <b-form-input
              id="uri"  v-model="form.uri" :disabled="uriGenerated" required :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Name -->
          <b-form-group  required>
              <opensilex-FormInputLabelHelper label=component.variable.entity-name helpMessage="component.variable.entity-name-help" >
              </opensilex-FormInputLabelHelper>
              <ValidationProvider 
                :name="$t('component.variable.entity-name')" 
                rules="required"
                v-slot="{ errors }"
              >                
              <b-form-input id="label"  v-model="form.label"
                  :placeholder="$t('component.variable.entity-name-placeholder')" >
              </b-form-input>
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
          </b-form-group>
          
        </b-form>
    </ValidationObserver>
    </b-modal>
</template>



<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";
import { EntityCreationDTO } from "opensilex-core/index";

@Component
export default class EntityForm extends Vue {

    title = "";
    uriGenerated = true;
    editMode = false;

    $opensilex: any;

    @Ref("modalRef") readonly modalRef!: any;
    @Ref("validatorRef") readonly validatorRef!: any;

    form: EntityCreationDTO = {
        uri: null,
        label: null,
        comment: null,
    }

    showCreateForm() {
        this.title = this.$t("component.variable.form.add.entity").toString();
        let modalRef: any = this.$refs.modalRef;
        modalRef.show();
    }

    hideForm() {
      let modalRef: any = this.modalRef;
      modalRef.hide();
    }

    onValidate() {
      return new Promise((resolve, reject) => {

        if (this.editMode) {
          this.$emit("onUpdate", this.form, result => {
            if (result instanceof Promise) {
              result.then(resolve).catch(reject);
            } else {
              resolve(result);
            }
          });
        } else {
          return this.$emit("onCreate", this.form, result => {
            if (result instanceof Promise) {
              result.then(resolve).catch(reject);
            } else {
              resolve(result);
            }
          });
        }
    });
  }

    validate() {

      let validatorRef: any = this.validatorRef;
      validatorRef.validate().then(isValid => {
        if (isValid) {
          if (this.uriGenerated && !this.editMode) {
            this.form.uri = null;
          }

          this.onValidate()
            .then(() => {
              this.$nextTick(() => {
                let modalRef: any = this.modalRef;
                modalRef.hide();
              });
            })
            .catch(error => {
              if (error.status == 409) {
                this.$opensilex.errorHandler(
                  error,
                  this.$i18n.t("component.user.errors.user-already-exists")
                );
              } else {
                this.$opensilex.errorHandler(error);
              }
            });
        }
    });
  }
}

</script>

<style scoped lang="scss">
</style>