<template>
    <b-modal ref="modalRef" @ok.prevent="validate" size="lg" :static="true">
    <template v-slot:modal-ok>{{$t('component.common.ok')}}</template>
    <template v-slot:modal-cancel>{{$t('component.common.cancel')}}</template>

    <template v-slot:modal-title>{{title}}</template>
    <ValidationObserver ref="validatorRef">

        <b-form>

        <!-- URI -->
        <b-form-group >
            <opensilex-FormInputLabelHelper label=component.variable.entity-uri helpMessage="component.variable.entity-uri-help"  ></opensilex-FormInputLabelHelper>
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox v-if="!editMode" id="autogenerated" v-model="uriGenerated"  name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}
            </b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider name="uri" rules="required_if:autogenerated,false|url" v-slot="{ errors }">
            <b-form-input
              id="uri"  v-model="form.uri" :disabled="uriGenerated"  type="text"  required :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Name -->
          <b-form-group  required  >
              <opensilex-FormInputLabelHelper label=component.variable.entity-name helpMessage="component.variable.entity-name-help" >
              </opensilex-FormInputLabelHelper>
              <ValidationProvider :name="$t('component.variable.entity-name')" v-slot="{ errors }">                
              <b-form-input  id="label"  v-model="form.label"  type="textinput"
                  :placeholder="$t('component.variable.entity-name-placeholder')" >
              </b-form-input>
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
          </b-form-group>
          
        </b-form>
    </ValidationObserver>
    </b-modal>
</template>



<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";

@Component
export default class EntityForm extends Vue {

    title = "";
    uriGenerated = true;
    editMode = false;

    form: any = {
        uri: null,
        name: null
    }

    showCreateForm() {
        this.title = this.$t("component.variable.form.add.entity").toString();
        let modalRef: any = this.$refs.modalRef;
        modalRef.show();
    }
}

</script>

<style scoped lang="scss">
</style>