<template>
  <div ref="modalRef" @ok.prevent="validate">
    <ValidationObserver ref="validatorRef">
      <b-form>
        <!-- URI -->
        <b-form-group >
            <opensilex-FormInputLabelHelper label=component.variable.uri helpMessage="component.variable.uri-help"  ></opensilex-FormInputLabelHelper>
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox v-if="!editMode" id="autogenerated" v-model="uriGenerated"  name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}
            </b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider name="uri" rules="required_if:autogenerated,false|url" v-slot="{ errors }">
            <b-form-input
              id="uri"  v-model="form.uri" :disabled="uriGenerated"  type="text"  required :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Entity -->
        <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.entity helpMessage="component.variable.entity-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.entity')" v-slot="{ errors }">
          <b-form-select id="entityList" v-model="form.entityUri" :options="entityList" > </b-form-select>
          <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Quality -->
        <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.quality helpMessage="component.variable.quality-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.quality')" v-slot="{ errors }">
          <b-form-select id="qualityList" v-model="form.qualityUri" :options="qualityList" > </b-form-select>
          <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

         <!-- fullname -->
         <b-form-group >
          <opensilex-FormInputLabelHelper label=component.variable.fullname helpMessage="component.variable.fullname-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.fullname')" v-slot="{ errors }">
            <b-form-input  id="fullname"  v-model="form.fullname"  type="textinput">
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

          <!-- label -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.label helpMessage="component.variable.label-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.label')" v-slot="{ errors }">
            <b-form-input  id="label"  v-model="form.label"  type="textinput"
              :placeholder="$t('component.variable.label-placeholder')" >
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

         <!-- Trait name -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.trait-name helpMessage="component.variable.trait-name-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.trait-name')" v-slot="{ errors }">
            <b-form-input  id="traitName"  v-model="form.traitName"  type="textinput"
              :placeholder="$t('component.variable.trait-name-placeholder')" >
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Trait uri -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.trait-uri helpMessage="component.variable.trait-uri-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.trait-uri')" v-slot="{ errors }">
            <b-form-input  id="traitUri"  v-model="form.traitUri"  type="textinput"
              :placeholder="$t('component.variable.trait-uri-placeholder')" >
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

         <!-- Method name -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.method-name helpMessage="component.variable.method-name-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.method-name')" v-slot="{ errors }">
            <b-form-input  id="methodName"  v-model="form.methodName"  type="textinput"
              :placeholder="$t('component.variable.method-name-placeholder')" >
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Method uri -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.method-uri helpMessage="component.variable.method-uri-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.method-uri')" v-slot="{ errors }">
            <b-form-input  id="methodUri"  v-model="form.methodUri"  type="textinput"
              :placeholder="$t('component.variable.method-uri-placeholder')" >
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Method description -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.method-description helpMessage="component.variable.method-description-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.method-description')" v-slot="{ errors }">
            <b-form-input  id="methodDescription"  v-model="form.methodDescription"  type="textinput"
              :placeholder="$t('component.variable.method-description-placeholder')" >
            </b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        <!-- Method external reference -->
        <!-- <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.method-reference helpMessage="component.variable.method-reference-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.method-reference')" v-slot="{ errors }">
            <b-form-textinput  id="methodRe"  v-model="form.methodDescription"  type="textinput"
              :placeholder="$t('component.variable.method-description-placeholder')" >
            </b-form-textinput>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group> -->

    </b-form>
    </ValidationObserver>
  </div>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";

@Component
export default class VariableForm extends Vue{

uriGenerated = true;

form: any;

entityList: any;
qualityList: any;
methodList: any;
traitList: any;

created(){

    this.entityList = ["entityA","entityB","entityC"];
    this.qualityList = ["qualityA","qualityB"];
    this.methodList = ["methodA","methodB"];
    this.traitList = ["traitA","traitB"];

    this.form = {
        uri: null,
        entityUri : null,
        qualityUri: null,
        fullname: null,
        label: null,
        traitName : null,
        traitUri : null,
        methodName: null,
        methodUri: null,
        methodDescription: null
    }
}

}

</script>
<style scoped lang="scss">
</style>
