<template>
  <div ref="modalRef" @ok.prevent="validate">
    <ValidationObserver ref="validatorRef">
      <b-form>
        <!-- URI -->
        <b-form-group >
            <opensilex-FormInputLabelHelper label=component.variable.uri helpMessage="component.variable.uri-help"  ></opensilex-FormInputLabelHelper>
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox v-if="!editMode" id="autogenerated" v-model="uriGenerated"  name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}
            </b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider name="uri" rules="required_if:autogenerated,false|url" v-slot="{ errors }">
            <b-form-input
              id="uri"  v-model="form.uri" :disabled="uriGenerated"  type="text"  required :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>


    <div class="row">
            <div class="col-lg-3">

          <!-- label -->
          <b-form-group  required  >
              <opensilex-FormInputLabelHelper label=component.variable.label helpMessage="component.variable.label-help" >
              </opensilex-FormInputLabelHelper>
              <ValidationProvider :name="$t('component.variable.label')" v-slot="{ errors }">                
              <b-form-input  id="label"  v-model="form.label"  type="textinput"
                  :placeholder="$t('component.variable.label-placeholder')" >
              </b-form-input>
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
          </b-form-group>

          </div>

          <div class="col-lg-3">
             <!-- fullname -->
              <b-form-group >
                  <opensilex-FormInputLabelHelper label=component.variable.fullname helpMessage="component.variable.fullname-help" >
                  </opensilex-FormInputLabelHelper>
                  <ValidationProvider :name="$t('component.variable.fullname')" v-slot="{ errors }">
                    <b-form-input  id="fullname"  v-model="form.fullname"  type="textinput">
                    </b-form-input>
                    <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                  </ValidationProvider>
            </b-form-group>
          </div>
      </div>

        <div class="row">
            <div class="col-lg-3">
            <!-- Entity -->
            <b-form-group  required  >
                <opensilex-FormInputLabelHelper label=component.variable.entity helpMessage="component.variable.entity-help" >
                </opensilex-FormInputLabelHelper>
                <ValidationProvider :name="$t('component.variable.entity')" v-slot="{ errors }">
                <multiselect
                        :limit="1"
                        :closeOnSelect="false"
                        :placeholder="$t('component.variable.form.placeholder.entity')"
                        v-model="form.entity"
                        :options="entityList"
                        selectLabel=""
                        selectedLabel="X"
                        deselectLabel="X"
                        :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                />
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                </ValidationProvider>   
              <b-button variant="primary">{{$t('component.variable.form.add.entity')}}</b-button>        
              </b-form-group>   
              </div>

               <div class="col-lg-3">  
                  <!-- Quality -->
              <b-form-group  required  >
                  <opensilex-FormInputLabelHelper label=component.variable.quality helpMessage="component.variable.quality-help" >
                  </opensilex-FormInputLabelHelper>
                  <ValidationProvider :name="$t('component.variable.quality')" v-slot="{ errors }">
                  <multiselect
                          :placeholder="$t('component.variable.form.placeholder.quality')"
                          :limit="1"
                          :closeOnSelect="false"
                          v-model="form.quality"
                          :options="qualityList"
                          selectLabel=""
                          selectedLabel="X"
                          deselectLabel="X"
                          :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                  />
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
              <b-button variant="primary">{{$t('component.variable.form.add.quality')}}</b-button>        
            </b-form-group>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
              <!-- Method uri -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.method helpMessage="component.variable.method-uri-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.method-uri')" v-slot="{ errors }">
          <multiselect
                  :placeholder="$t('component.variable.form.placeholder.method')"
                  :limit="1"
                  :closeOnSelect="false"
                  v-model="form.method"
                  :options="methodList"
                  selectLabel=""
                  selectedLabel="X"
                  deselectLabel="X"
                  :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
          />
          <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
          <b-button variant="primary">{{$t('component.variable.form.add.method')}}</b-button>        
        </b-form-group>

         </div>
            <div class="col-lg-3">
              <!-- Scale -->
              <b-form-group  required  >
                <opensilex-FormInputLabelHelper label=component.variable.scale helpMessage="component.variable.scale-help" >
                </opensilex-FormInputLabelHelper>
                <ValidationProvider :name="$t('component.variable.scale')" v-slot="{ errors }">
                <multiselect
                        :placeholder="$t('component.variable.form.placeholder.scale')"
                        :limit="1"
                        :closeOnSelect="false"
                        v-model="form.scale"
                        :options="scaleList"
                        selectLabel=""
                        selectedLabel="X"
                        deselectLabel="X"
                        :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                />
                  <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                </ValidationProvider>
                <b-button variant="primary">{{$t('component.variable.form.add.scale')}}</b-button>        
              </b-form-group>   
          </div>
        </div>         

        <div>
          <div class="col-lg-3">

             <!-- description -->
          <b-form-group >
              <opensilex-FormInputLabelHelper label=component.variable.description helpMessage="component.variable.description-help" >
              </opensilex-FormInputLabelHelper>
              <ValidationProvider :name="$t('component.variable.description')" v-slot="{ errors }">
                <b-textarea  id="description"  v-model="form.description"  type="textarea">
                </b-textarea>
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
          </b-form-group>

          </div>
        </div>

        <div class="row">
            <div class="col-lg-3">

        <!-- Trait uri -->
         <b-form-group  >
          <opensilex-FormInputLabelHelper label=component.variable.trait-uri helpMessage="component.variable.trait-uri-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.trait-uri')" v-slot="{ errors }">

          <multiselect
                        :placeholder="$t('component.variable.form.placeholder.trait')"
                        :limit="1"
                        :closeOnSelect="false"
                        v-model="form.trait"
                        :options="traitList"
                        selectLabel=""
                        selectedLabel="X"
                        deselectLabel="X"
                        :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
            />
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>

        </div>
        </div>


        

    </b-form>
    </ValidationObserver>
  </div>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";

@Component
export default class VariableForm extends Vue{

uriGenerated = true;

form: any;

entityList: any;
qualityList: any;
methodList: any;
traitList: any;
scaleList : any;

created(){

    this.entityList = ["Air","Leaf","Precipitation","Wind"];
    this.qualityList = ["Temperature","Diameter","Speed","Area"];
    this.methodList = ["Sensor","Pressure chamber","Rainfall 10 minutes","Area per dry mass unit"];
    this.traitList = ["Air relative humidity","Leaf Area","Wind speed"];
    this.scaleList = ["Celcius degree","cm","m","km","Bar","Gram per liter","Percentage"];

    this.form = {
        uri: null,
        entity : null,
        quality: null,
        fullname: null,
        label: null,
        description: null,
        trait: null,
        method : null,
        scale : null
    }
}

}

</script>
<style scoped lang="scss">
</style>
