<template>
  <div ref="modalRef" @ok.prevent="validate">
    <ValidationObserver ref="validatorRef">
      <b-form>
        <!-- URI -->
        <b-form-group >
            <opensilex-FormInputLabelHelper label=component.variable.uri helpMessage="component.variable.uri-help"  ></opensilex-FormInputLabelHelper>
          <ValidationProvider vid="autogenerated">
            <b-form-checkbox v-if="!editMode" id="autogenerated" v-model="uriGenerated"  name="autogenerated"
            >{{$t('component.common.autogenerated-uri')}}
            </b-form-checkbox>
          </ValidationProvider>
          <ValidationProvider name="uri" rules="required_if:autogenerated,false|url" v-slot="{ errors }">
            <b-form-input
              id="uri"  v-model="form.uri" :disabled="uriGenerated" required :placeholder="$t('component.common.autogenerated-uri')"
            ></b-form-input>
            <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
        </b-form-group>


    <div class="row">
          <div class="col-lg-3">

          <!-- label -->
          <b-form-group  required  >
              <opensilex-FormInputLabelHelper label=component.variable.label helpMessage="component.variable.label-help" >
              </opensilex-FormInputLabelHelper>
              <ValidationProvider :name="$t('component.variable.label')" v-slot="{ errors }">                
              <b-form-input  id="label"  v-model="form.label" 
                  :placeholder="$t('component.variable.label-placeholder')" >
              </b-form-input>
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
          </b-form-group>

          </div>

          <div class="col-lg-3">
             <!-- longname -->
              <b-form-group >
                  <opensilex-FormInputLabelHelper label=component.variable.longname helpMessage="component.variable.longname-help" >
                  </opensilex-FormInputLabelHelper>
                  <ValidationProvider :name="$t('component.variable.longname')" v-slot="{ errors }">
                    <b-form-input  id="longname"  v-model="form.longname">
                    </b-form-input>
                    <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                  </ValidationProvider>
            </b-form-group>
          </div>
      </div>

      <div class="col-lg-3">
            <!-- description -->
        <b-form-group >
            <opensilex-FormInputLabelHelper label=component.variable.description helpMessage="component.variable.description-help" >
            </opensilex-FormInputLabelHelper>
            <ValidationProvider :name="$t('component.variable.description')" v-slot="{ errors }">
              <b-textarea  id="description"  v-model="form.description" >
              </b-textarea>
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
            </ValidationProvider>
        </b-form-group>
      </div>

        <div class="row">
            <div class="col-lg-3">
            <!-- Entity -->
            <b-form-group  required  >
                <opensilex-FormInputLabelHelper label=component.variable.entity helpMessage="component.variable.entity-help" >
                </opensilex-FormInputLabelHelper>
                <ValidationProvider :name="$t('component.variable.entity')" v-slot="{ errors }">
                <multiselect
                        :limit="1"
                        :closeOnSelect=true
                        :placeholder="$t('component.variable.form.placeholder.entity')"
                        v-model="form.entity"
                        :options="entityList"
                        :custom-label="dto => dto.label"
                        deselectLabel="You must select one element"
                        track-by="uri"
                        :allow-empty=false
                        :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                />
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                </ValidationProvider>   
                <b-button @click="showEntityCreateForm"
                  variant="primary">{{$t('component.variable.form.add.entity')}}              
                </b-button>   

                <opensilex-EntityForm
                  ref="entityForm"
                  @onCreate="callCreateEntityService">
                </opensilex-EntityForm>     
              </b-form-group>   
              </div>

               <div class="col-lg-3">  
                  <!-- Quality -->
              <b-form-group  required  >
                  <opensilex-FormInputLabelHelper label=component.variable.quality helpMessage="component.variable.quality-help" >
                  </opensilex-FormInputLabelHelper>
                  <ValidationProvider :name="$t('component.variable.quality')" v-slot="{ errors }">
                  <multiselect
                        :limit="1"
                        :closeOnSelect=true
                        :placeholder="$t('component.variable.form.placeholder.quality')"
                        v-model="form.quality"
                        :options="qualityList"
                        :custom-label="dto => dto.label"
                        deselectLabel="You must select one element"
                        track-by="uri"
                        :allow-empty=false
                        :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                  />
              <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
              <b-button 
                  @click="showQualityCreateForm"
                  variant="primary">{{$t('component.variable.form.add.quality')}}
              </b-button>  

                <opensilex-QualityForm
                  ref="qualityForm"
                  @onCreate="callCreateQualityService">
                </opensilex-QualityForm>    

            </b-form-group>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
             <!-- Trait uri -->
            <b-form-group  >
              <opensilex-FormInputLabelHelper label=component.variable.trait-uri helpMessage="component.variable.trait-uri-help" >
              </opensilex-FormInputLabelHelper>
              <ValidationProvider :name="$t('component.variable.trait-uri')" v-slot="{ errors }">

              <b-form-input  id="trait"  v-model="form.trait"
                  :placeholder="$t('component.variable.trait-uri-placeholder')" >
              </b-form-input>

              <!-- <multiselect
                            :placeholder="$t('component.variable.form.placeholder.trait')"
                            :limit="1"
                            :closeOnSelect="false"
                            v-model="form.trait"
                            :options="traitList"
                            selectLabel=""
                            selectedLabel="X"
                            deselectLabel="X"
                            :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                /> -->
                <div class="error-message alert alert-danger">{{ errors[0] }}</div>
              </ValidationProvider>
            </b-form-group>
        </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
              <!-- Method uri -->
         <b-form-group  required  >
          <opensilex-FormInputLabelHelper label=component.variable.method helpMessage="component.variable.method-uri-help" >
          </opensilex-FormInputLabelHelper>
          <ValidationProvider :name="$t('component.variable.method-uri')" v-slot="{ errors }">
          <multiselect
              :limit="1"
              :closeOnSelect=true
              :placeholder="$t('component.variable.form.placeholder.method')"
              v-model="form.method"
              :options="methodList"
              :custom-label="dto => dto.label"
              deselectLabel="You must select one element"
              track-by="uri"
              :allow-empty=false
              :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
          />
          <div class="error-message alert alert-danger">{{ errors[0] }}</div>
          </ValidationProvider>
          <b-button @click="showMethodCreateForm" variant="primary">{{$t('component.variable.form.add.method')}}</b-button>   
           <opensilex-MethodForm
                ref="methodForm"
                @onCreate="callCreateMethodService">
            </opensilex-MethodForm>          
        </b-form-group>

         </div>
            <div class="col-lg-3">
              <!-- Scale -->
              <b-form-group  required  >
                <opensilex-FormInputLabelHelper label=component.variable.scale helpMessage="component.variable.scale-help" >
                </opensilex-FormInputLabelHelper>
                <ValidationProvider :name="$t('component.variable.scale')" v-slot="{ errors }">
                <multiselect
                    :limit="1"
                    :closeOnSelect=true
                    :placeholder="$t('component.variable.form.placeholder.scale')"
                    v-model="form.scale"
                    :options="scaleList"
                    :custom-label="dto => dto.label"
                    deselectLabel="You must select one element"
                    track-by="uri"
                    :allow-empty=false
                    :limitText="count => $t('component.common.multiselect.label.x-more', {count: count})"
                />
                  <div class="error-message alert alert-danger">{{ errors[0] }}</div>
                </ValidationProvider>
                <b-button  @click="showScaleCreateForm" variant="primary">{{$t('component.variable.form.add.scale')}}</b-button>   
                <opensilex-ScaleForm
                  ref="scaleForm"
                  @onCreate="callCreateScaleService">
                </opensilex-ScaleForm>              
              </b-form-group>   
          </div>
        </div>         
    </b-form>
    </ValidationObserver>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Ref } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import { EntityCreationDTO, VariablesService, EntityGetDTO, QualityCreationDTO, QualityGetDTO, MethodGetDTO, MethodCreationDTO, UnitGetDTO, UnitCreationDTO } from "opensilex-core/index";
import HttpResponse, { OpenSilexResponse } from "opensilex-core/HttpResponse";

@Component
export default class VariableForm extends Vue{

  $opensilex: any;
  service: VariablesService;

  uriGenerated = true;

  form: any;

  entityList: Array<EntityGetDTO> = [];
  qualityList: Array<QualityGetDTO> = [];
  methodList: Array<MethodGetDTO> = [];
  traitList: any;
  scaleList : Array<UnitGetDTO> = [];

  @Ref("entityForm") readonly entityForm!: any;
  @Ref("qualityForm") readonly qualityForm!: any;
  @Ref("methodForm") readonly methodForm!: any;
  @Ref("scaleForm") readonly scaleForm!: any;


  showEntityCreateForm() {
      this.entityForm.showCreateForm();
  }

  showQualityCreateForm(){
      this.qualityForm.showCreateForm();
  }

  showMethodCreateForm(){
    this.methodForm.showCreateForm();
  }

  showScaleCreateForm(){
    this.scaleForm.showCreateForm();
  }

  created(){

      this.traitList = ["Air relative humidity","Leaf Area","Wind speed"];
      // this.scaleList = ["Celcius degree","cm","m","km","Bar","Gram per liter","Percentage"];

      this.form = {
          uri: null,
          entity : [],
          quality: null,
          longname: null,
          label: null,
          description: null,
          trait: null,
          method : null,
          scale : null
      } 
      this.service = this.$opensilex.getService("opensilex.VariablesService");
      this.loadEntities();
      this.loadQualities();
      this.loadMethods();
      this.loadScales();
  }

  loadEntities(){
    this.service.searchEntities(undefined,undefined,undefined,0,100)
    .then((http: HttpResponse<OpenSilexResponse<Array<EntityGetDTO>>>) => {
        for(let i=0; i<http.response.result.length; i++) {
            this.entityList.push(http.response.result[i]);
        }
    }).catch(this.$opensilex.errorHandler);  
  }

  loadQualities(){
    this.service.searchQualities(undefined,undefined,undefined,0,100)
    .then((http: HttpResponse<OpenSilexResponse<Array<QualityGetDTO>>>) => {
        for(let i=0; i<http.response.result.length; i++) {
            this.qualityList.push(http.response.result[i]);
        }
    }).catch(this.$opensilex.errorHandler);  
  }

  loadMethods(){
    this.service.searchMethods(undefined,undefined,undefined,0,100)
    .then((http: HttpResponse<OpenSilexResponse<Array<MethodGetDTO>>>) => {
        for(let i=0; i<http.response.result.length; i++) {
            this.methodList.push(http.response.result[i]);
        }
    }).catch(this.$opensilex.errorHandler);  
  }

  loadScales(){
    this.service.searchUnits(undefined,undefined,undefined,0,100)
    .then((http: HttpResponse<OpenSilexResponse<Array<UnitGetDTO>>>) => {
        for(let i=0; i<http.response.result.length; i++) {
            this.scaleList.push(http.response.result[i]);
        }
    }).catch(this.$opensilex.errorHandler);  
  }

  callCreateEntityService(dto: EntityCreationDTO, done) {
      done(
          this.service.createEntity(dto)
          .then((http: HttpResponse<OpenSilexResponse<any>>) => {
              dto.uri = http.response.result;
              this.entityList.push(dto);
        }).catch(this.$opensilex.errorHandler)
      );
  }

  callCreateQualityService(dto: QualityCreationDTO, done) {
      done(
          this.service.createQuality(dto)
          .then((http: HttpResponse<OpenSilexResponse<any>>) => {
              dto.uri = http.response.result;
              this.qualityList.push(dto);
        }).catch(this.$opensilex.errorHandler)
      );
  }

  callCreateMethodService(dto: MethodCreationDTO, done) {
      done(
          this.service.createMethod(dto)
          .then((http: HttpResponse<OpenSilexResponse<any>>) => {
              dto.uri = http.response.result;
              this.methodList.push(dto);
        }).catch(this.$opensilex.errorHandler)
      );
  }

  callCreateScaleService(dto: UnitCreationDTO, done) {
      done(
          this.service.createUnit(dto)
          .then((http: HttpResponse<OpenSilexResponse<any>>) => {
              dto.uri = http.response.result;
              this.scaleList.push(dto);
        }).catch(this.$opensilex.errorHandler)
      );
  }

}

</script>
<style scoped lang="scss">
</style>
