<template>
    <div>
        <opensilex-OntologyCsvImporter
            ref="importForm"
            :baseType="$opensilex.Oeso.SCIENTIFIC_OBJECT_TYPE_URI"
            successImportMsg="ScientificObjectCSVImporter.successImportMsg"
            :validateCSV="validateCSV"
            :uploadCSV="uploadCSV"
            @csvImported="onCsvImported($event)"
        >
            <template v-slot:icon>
                <opensilex-Icon icon="ik#ik-target" class="icon-title"/>
            </template>
            <template v-slot:help>
                <opensilex-ScientificObjectImportHelp></opensilex-ScientificObjectImportHelp>
            </template>
            <template v-slot:generator>
                <b-col cols="2">
                    <opensilex-Button
                        class="mr-2 greenThemeColor"
                        :small="false"
                        @click="templateGenerator.show()"
                        icon
                        label="DataView.buttons.generate-template"
                    ></opensilex-Button>
                    <opensilex-OntologyCsvTemplateGenerator
                        ref="templateGenerator"
                        :baseType="$opensilex.Oeso.SCIENTIFIC_OBJECT_TYPE_URI"
                        templatePrefix="scientific_object"
                        typePlaceholder="OntologyObjectForm.form-type-placeholder"
                        uriHelp="ScientificObjectCSVImporter.uri-help"
                        uriExample="ScientificObjectCSVImporter.uri-example"
                        typeHelp="ScientificObjectCSVImporter.type-help"
                        typeExample="ScientificObjectCSVImporter.type-example"
                        :extraHeadersAndDescriptions="moveDescriptionGeneratorsPerMoveHeader"
                    ></opensilex-OntologyCsvTemplateGenerator>
                </b-col>
            </template>
        </opensilex-OntologyCsvImporter>
    </div>
</template>

<script lang="ts">
import {Component, Prop, Ref} from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import OpenSilexVuePlugin from "../../models/OpenSilexVuePlugin";
import {Store} from "vuex";
import OntologyCsvImporter from '../ontology/csv/OntologyCsvImporter.vue';
import OntologyCsvTemplateGenerator from "../ontology/csv/OntologyCsvTemplateGenerator.vue";
import {DescriptionGeneratorInformation} from "../../components/ontology/csv/OntologyCsvTemplateGenerator.vue";
import GenerateEventTemplate from "../../components/events/form/csv/GenerateEventTemplate.vue";

@Component
export default class ScientificObjectCSVImporter extends Vue {
    $opensilex: OpenSilexVuePlugin;
    $store: Store<any>;
    $router: VueRouter;


    @Ref("importForm") readonly importForm!: OntologyCsvImporter;
    @Ref("templateGenerator") readonly templateGenerator!: OntologyCsvTemplateGenerator;
    @Ref("resultModal") readonly resultModal!: any;

    @Prop({
        default: undefined
    })
    experimentURI;

    private readonly moveDescriptionGeneratorsPerMoveHeader: Map<string, DescriptionGeneratorInformation> = new Map<string, DescriptionGeneratorInformation>([
      ["start_date_of_Location", {propertyTranslationKey: "component.scientificObjects.geometry.startHelp", required: false, example: "component.events.start-example"}],
      ["end_date_of_Location", {propertyTranslationKey: "component.scientificObjects.geometry.endHelp", required: false, example: "component.events.start-example"}],
      ...GenerateEventTemplate.MOVE_DESCRIPTION_GENERATOR_BY_HEADER
    ]);

    get user() {
        return this.$store.state.user;
    }

    get lang() {
        return this.$store.state.lang;
    }

    show() {
        this.importForm.show();
    }

    nbLinesImported = 0;

    validateCSV(csvFile) {
        return this.$opensilex.uploadFileToService(
            "/core/scientific_objects/import_validation",
            {
                description: {
                    experiment: this.experimentURI,
                },
                file: csvFile,
            },
            null,
            null
        );
    }

    uploadCSV(validationToken: string, csvFile) {
        return this.$opensilex.uploadFileToService(
            "/core/scientific_objects/import",
            {
                description: {
                    experiment: this.experimentURI,
                    validationToken: validationToken
                },
                file: csvFile,
            },
            null,
            null
        );
    }

    onCsvImported(response) {
        this.$emit("csvImported", response);
    }
}
</script>

<style scoped lang="scss">
</style>

<i18n>
en:
    ScientificObjectCSVImporter:
        import-title: Import scientific objects
        successImportMsg: "scientific object(s) imported"
        uri-example: http://opensilex.org/id/scientific-object/so-name1
        uri-help: Scientific object URI (autogenerated if empty)
        type-example: vocabulary:Plant
        type-help: "URI of the object type"

fr:
    ScientificObjectCSVImporter:
        import-title: Importer des objets scientifiques
        successImportMsg: "objet(s) scientifique importé(s)"
        uri-example: http://opensilex.org/id/scientific-object/so-nom1
        uri-help: URI de l'objet scientifique (auto-générée si vide)
        type-example: vocabulary:Plant
        type-help: "URI du type d'objet scientifique"
</i18n>