//******************************************************************************
//                             FileInformationDTO.java 
// SILEX-PHIS
// Copyright © INRA 2017
// Creation date: 8 December 2017
// Contact: morgane.vidal@inra.fr, anne.tireau@inra.fr, pascal.neveu@inra.fr
//******************************************************************************
package opensilex.service.resource.dto;

import io.swagger.annotations.ApiModelProperty;
import opensilex.service.documentation.DocumentationAnnotation;
import opensilex.service.resource.validation.interfaces.Required;
import opensilex.service.resource.dto.manager.AbstractVerifiedClass;
import opensilex.service.model.FileInformations;

/**
 * File information DTO.
 * @author Morgane Vidal <morgane.vidal@inra.fr>
 */
public class FileInformationDTO extends AbstractVerifiedClass {

    /**
     * The checksum is generated by the md5sum
     */
    private String checksum;
    
    /**
     * The file extension
     * @example PNG
     */
    private String extension;

    @Override
    public FileInformations createObjectFromDTO() {
        FileInformations fileInformations = new FileInformations();
        fileInformations.setChecksum(checksum);
        fileInformations.setExtension(extension);
        return fileInformations;
    }

    @Required
    @ApiModelProperty(example = DocumentationAnnotation.EXAMPLE_FILE_INFORMATION_CHECKSUM)
    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    
    @Required
    @ApiModelProperty(example = DocumentationAnnotation.EXAMPLE_FILE_INFORMATION_EXTENSION)
    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }
}
