//******************************************************************************
//                            DocumentMetadataDTO.java 
// SILEX-PHIS
// Copyright © INRA 2017
// Creation date: March 2017
// Contact: arnaud.charleroy@inra.fr, morgane.vidal@inra.fr, anne.tireau@inra.fr, 
//          pascal.neveu@inra.fr
//******************************************************************************
package opensilex.service.resource.dto;

import io.swagger.annotations.ApiModelProperty;
import java.util.List;
import javax.validation.Valid;
import opensilex.service.configuration.DateFormat;
import opensilex.service.resource.validation.interfaces.Required;
import opensilex.service.resource.dto.manager.AbstractVerifiedClass;
import opensilex.service.resource.validation.interfaces.Date;
import opensilex.service.resource.validation.interfaces.DocumentStatus;
import opensilex.service.resource.validation.interfaces.URL;

/**
 * Document metadata DTO.
 * @author Morgane Vidal <morgane.vidal@inra.fr>
 */
public class DocumentMetadataDTO extends AbstractVerifiedClass {
    
    /**
     * SILEX:info
     * not used in POST
     * /SILEX:info
     */
    private String uri;
    private String documentType;
    private String checksum;
    private String creator;
    
    /**
     * should follow the RFC4646 norm
     */
    private String language;
    private String title;
    private String creationDate;
    private String extension;
    private String comment;
    private List<ConcernedItemDTO> concernedItems;
    
    /**
     * @example linked when the object to which it is linked exists, unlinked
     * otherwise
     */
    private String status;  
    
    /**
     * Generated by the web service
     */
    private String serverFilePath;

    @Override
    public Object createObjectFromDTO() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @URL
    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    @URL
    @Required
    @ApiModelProperty(example = "http://www.phenome-fppn.fr/vocabulary/2015#ScientificDocument")
    public String getDocumentType() {
        return documentType;
    }

    public void setDocumentType(String mediaType) {
        this.documentType = mediaType;
    }
    
    @ApiModelProperty(example = "106fa487baa1728083747de1c6df73e9")
    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    
    @ApiModelProperty(example = "John Doe")
    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    @ApiModelProperty(example = "fr")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }
    
    @ApiModelProperty(example = "title")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Date(DateFormat.YMD)
    @ApiModelProperty(example = "2017-01-01")
    public String getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }
    
    @Valid
    public List<ConcernedItemDTO> getConcernedItems() {
        return concernedItems;
    }

    public void setConcernedItems(List<ConcernedItemDTO> concernedItems) {
        this.concernedItems = concernedItems;
    }
    
    @ApiModelProperty(example = "jpg")
    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getServerFilePath() {
        return serverFilePath;
    }

    public void setServerFilePath(String serverFilePath) {
        this.serverFilePath = serverFilePath;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Required
    @DocumentStatus
    @ApiModelProperty(example = "linked")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
