<template>
  <b-modal ref="modalRef" @ok.prevent="validate">
    <template v-slot:modal-title>{{title}}</template>
    <b-form ref="formRef">
      <b-form-group label="User URI:" label-for="uri">
        <b-form-checkbox
          v-if="!editMode"
          id="autogenerated"
          v-model="uriGenerated"
          name="autogenerated"
        >Auto-generate URI</b-form-checkbox>
        <b-form-input
          id="uri"
          v-model="form.uri"
          :disabled="uriGenerated"
          type="text"
          required
          placeholder="Auto-generated URI"
        ></b-form-input>
      </b-form-group>
      <b-form-group label="Email address:" label-for="email" required>
        <b-form-input
          id="email"
          v-model="form.email"
          type="email"
          required
          placeholder="Enter email"
          autocomplete="no"
        ></b-form-input>
      </b-form-group>
      <b-form-group label="Password:" label-for="password">
        <b-form-input
          id="password"
          v-model="form.password"
          type="password"
          placeholder="Enter password"
          autocomplete="new-password"
        ></b-form-input>
      </b-form-group>
      <b-form-group label="First name:" label-for="firstName" required>
        <b-form-input
          id="firstName"
          v-model="form.firstName"
          type="text"
          required
          placeholder="Enter first name"
        ></b-form-input>
      </b-form-group>
      <b-form-group label="Last name:" label-for="lastName" required>
        <b-form-input
          id="lastName"
          v-model="form.lastName"
          type="text"
          required
          placeholder="Enter last name"
        ></b-form-input>
      </b-form-group>
    </b-form>
  </b-modal>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import VueRouter from "vue-router";
import { UserCreationDTO } from "opensilex-rest/index";

@Component
export default class UserForm extends Vue {
  $opensilex: any;
  $store: any;
  $router: VueRouter;

  get user() {
    return this.$store.state.user;
  }

  uriGenerated = true;

  form: UserCreationDTO = {
    uri: "",
    email: "",
    firstName: "",
    lastName: "",
    admin: false,
    password: ""
  };

  title = "Add user";

  editMode = false;

  clearForm() {
    this.form = {
      uri: "",
      email: "",
      firstName: "",
      lastName: "",
      admin: false,
      password: ""
    };
  }
  showCreateForm() {
    this.clearForm();
    this.editMode = false;
    this.title = "Add user";
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  showEditForm(form: UserCreationDTO) {
    this.form = form;
    this.editMode = true;
    this.title = "Update user";
    this.uriGenerated = true;
    let modalRef: any = this.$refs.modalRef;
    modalRef.show();
  }

  hideForm() {
    let modalRef: any = this.$refs.modalRef;
    modalRef.hide();
  }

  onValidate() {
    return new Promise((resolve, reject) => {
      if (this.editMode) {
        this.$emit("onUpdate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      } else {
        return this.$emit("onCreate", this.form, result => {
          if (result instanceof Promise) {
            result.then(resolve).catch(reject);
          } else {
            resolve(result);
          }
        });
      }
    });
  }

  validate() {
    let formRef: any = this.$refs.formRef;
    if (formRef.checkValidity()) {
      if (this.uriGenerated && !this.editMode) {
        this.form.uri = null;
      }

      this.onValidate()
        .then(() => {
          this.$nextTick(() => {
            let modalRef: any = this.$refs.modalRef;
            modalRef.hide();
          });
        })
        .catch(error => {
          if (error.status == 409) {
            // TODO display error message user already exists
            console.error("TODO display error message user already exists");
          } else {
            this.$opensilex.errorHandler(error);
          }
        });
    } else {
      // TODO validation error management
      console.error("TODO validation error management");
    }
  }
}
</script>

<style scoped lang="scss">
</style>

