<template>
  <b-form-group>
    <opensilex-FormInputLabelHelper
      :label="label"
      helpMessage="component.common.uri.help-message"
      labelFor="uri"
    ></opensilex-FormInputLabelHelper>
    <ValidationProvider vid="autogenerated">
      <b-form-checkbox
        v-if="!editMode"
        id="autogenerated"
        v-model="uriGenerated"
        name="autogenerated"
      >{{$t('component.common.autogenerated-uri')}}</b-form-checkbox>
    </ValidationProvider>
    <ValidationProvider name="uri" rules="required_if:autogenerated,false|url" v-slot="{ errors }">
      <b-form-input
        id="uri"
        v-model="uri"
        :disabled="uriGenerated"
        type="text"
        required
        :placeholder="$t('component.common.autogenerated-uri')"
      ></b-form-input>
      <div class="error-message alert alert-danger">{{ errors[0] }}</div>
    </ValidationProvider>
  </b-form-group>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";

@Component
export default class FormAutogenerateURI extends Vue {
  @Prop()
  uri;

  @Prop()
  label;

  @Prop()
  editMode;

  @Prop()
  uriGenerated;
}
</script>

<style scoped lang="scss">
</style>
