/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";


import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class AngularService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Return the current configuration
     * 
     
     */
    public config(observe?: 'body', headers?: Headers): Observable<any>;
    public config(observe?: 'response', headers?: Headers): Observable<HttpResponse<any>>;
    public config(observe: any = 'body', headers: Headers = {}): Observable<any> {
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<any>> = this.httpClient.get(`${this.basePath}/angular/config`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <any>(httpResponse.response));
        }
        return response;
    }
    /**
     * Return the angular plugin sources
     * 
     * @param module 
     * @param plugin 
     
     */
    public pluginByName(module: string, plugin: string, observe?: 'body', headers?: Headers): Observable<any>;
    public pluginByName(module: string, plugin: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<any>>;
    public pluginByName(module: string, plugin: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!module){
            throw new Error('Required parameter module was null or undefined when calling pluginByName.');
        }

        if (!plugin){
            throw new Error('Required parameter plugin was null or undefined when calling pluginByName.');
        }

        headers['Accept'] = 'application/octet-stream';

        const response: Observable<HttpResponse<any>> = this.httpClient.get(`${this.basePath}/angular/plugin/${encodeURIComponent(String(module))}/${encodeURIComponent(String(plugin))}.js`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <any>(httpResponse.response));
        }
        return response;
    }
}
