/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OntologyReference } from './ontologyReference';


export interface VariableUpdateDTO { 
    label?: string;
    comment?: string;
    entity: string;
    quality: string;
    method: string;
    unit: string;
    relations?: Array<OntologyReference>;
}
