name: trigger gitlab job
on: push
jobs:
 update_gitlab_upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:  curl
      run: |
        git clone https://oauth2:${{ secrets.FORGEMIA_PAT }}@forgemia.inra.fr/OpenSILEX/opensilex-dev.git
        cd opensilex-dev/
        git fetch origin
        git checkout upstream 2>/dev/null || git checkout -b upstream
        git pull https://github.com/OpenSILEX/opensilex.git master
        git push origin upstream
